const project2019 = [
  {
    no: "1",
    field:
      "Preparation of Regional Action Plans (RAD) Activities of Disaster Management Plans (RPB)",
    subField: "Study Services, Research and Technical Assistance",
    location: "Sumedang District",
    name: "Regional Disaster Management Agency (BPBD)",
    address: "Jl. Empang No. 01 Sumedang 45312",
    numberDate: "02.1/SPK/RAD/BPBD /2019 5/3/2019",
    value: "90.948.000",
    contract: "3/4/2019",
    handover: "3/4/2019",
  },
  {
    no: "2",
    field: "Pedestrian Bridge Planning Consultant Services",
    subField: "Transportation Civil Engineering Engineering",
    location: "Bandung City",
    name: "Bandung City Department of Transportation",
    address: "Jl. Soekarno Hatta No.205",
    numberDate: "03/PPK-PPSTK- PPJPO/II/DISHUB/20 19 12/2/2019",
    value: "98.395.000",
    contract: "12/4/2019",
    handover: "12/4/2019",
  },
  {
    no: "3",
    field:
      "Consultancy Services for Heavy Rehabilitation Planning of SDN Tanjung Priok Building 02/03",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "DKI Jakarta",
    name: "Region I Education Office North Jakarta Administrative City",
    address: "Jl. Laksda Yos Sudarso No.27-29",
    numberDate: "463/1.851.2.061 12/2/2019",
    value: "76.700.000",
    contract: "13/03/2019",
    handover: "13/03/2019",
  },
  {
    no: "4",
    field:
      "Preparation of DED for the Development of the Senopati & Bendungan Hilir Waste Water Pipeline Network",
    subField: "Water Civil Engineering Engineering",
    location: "South Jakarta and Central Jakarta",
    name: "PD PAL JAYA Provincial Government of DKI Jakarta",
    address: "Jl. Sultan Agung No.1",
    numberDate: "528/-1.712.8 29/04/2019",
    value: "292.248.000",
    contract: "27/07/2019",
    handover: "27/07/2019",
  },
  {
    no: "5",
    field: "Technical Advice on Strengthening the Ciliman River Bank",
    subField: "Water Civil Engineering Engineering",
    location: "Banten Province",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Syech Nawawi Al-Batani, Curug- Palima",
    numberDate: "900/SP.18.2.9/PJSA- DPUPR/IV/2019 30/04/2019",
    value: "88.694.000",
    contract: "30/07/2019",
    handover: "30/07/2019",
  },
  {
    no: "6",
    field:
      "Equipment and Machinery Capital Expenditures - Procurement of Other Office Equipment",
    subField: "Other Service",
    location: "Karang Asem Regency",
    name: "Department of Youth and Sports Education",
    address: "Jl. Veteran (Jalur 11) - Amlapura",
    numberDate: "027/17/SET/VI/Disdi kpora/2019 11/6/2019",
    value: "195.992.500",
    contract: "9/9/2019",
    handover: "9/9/2019",
  },
];

export default project2019;
