const project2020 = [
  {
    no: "1",
    field:
      "Planning for the development of the G. Marapi Observation Post Center for Volcanology and Geological Hazard Mitigation, Geological agency",
    subField: "Architectural Planning",
    location: "Bandung",
    name: "Ministry of Energy & Mineral Resources Geology Agency",
    address: "Jl. Diponogoro No. 57 Bandung",
    numberDate: "10/SPK-PL/Perencanaan Pos Marapi/PPK- III/PVG/2020 17/03/2020",
    value: "98.868.000",
    contract: "17/03/2020",
    handover: "15/03/2020",
  },
  {
    no: "2",
    field: "Preparation of Disaster Risk Assessment (KRB)",
    subField: "Study Services, Research and Technical Assistance",
    location: "Sumedang",
    name: "Sumedang Regional Disaster Management Agency",
    address: "Jl. Empang No. 1 Sumedang",
    numberDate: "03.06/SPK/PPK- KRBTL/BPBD/2020 20/03/2020",
    value: "85.030.000",
    contract: "18/04/2020",
    handover: "18/04/2020",
  },
  {
    no: "3",
    field:
      "Consultancy Services for Heavy Rehabilitation Planning of SDN Tanjung Priok Building 02/03",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "DKI Jakarta",
    name: "Region I Education Office North Jakarta Administrative City",
    address: "Jl. Laksda Yos Sudarso No.27-29",
    numberDate: "463/1.851.2.061 12/2/2019",
    value: "76.700.000",
    contract: "13/03/2019",
    handover: "13/03/2019",
  },
  {
    no: "4",
    field:
      "Preparation of DED for the Development of the Senopati & Bendungan Hilir Waste Water Pipeline Network",
    subField: "Water Civil Engineering Engineering",
    location: "South Jakarta and Central Jakarta",
    name: "PD PAL JAYA Provincial Government of DKI Jakarta",
    address: "Jl. Sultan Agung No.1",
    numberDate: "528/-1.712.8 29/04/2019",
    value: "292.248.000",
    contract: "27/07/2019",
    handover: "27/07/2019",
  },
  {
    no: "5",
    field: "Technical Advice on Strengthening the Ciliman River Bank",
    subField: "Water Civil Engineering Engineering",
    location: "Banten Province",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Syech Nawawi Al-Batani, Curug- Palima",
    numberDate: "900/SP.18.2.9/PJSA- DPUPR/IV/2019 30/04/2019",
    value: "88.694.000",
    contract: "30/07/2019",
    handover: "30/07/2019",
  },
  {
    no: "6",
    field:
      "Equipment and Machinery Capital Expenditures - Procurement of Other Office Equipment",
    subField: "Other Service",
    location: "Karang Asem Regency",
    name: "Department of Youth and Sports Education",
    address: "Jl. Veteran (Jalur 11) - Amlapura",
    numberDate: "027/17/SET/VI/Disdi kpora/2019 11/6/2019",
    value: "195.992.500",
    contract: "9/9/2019",
    handover: "9/9/2019",
  },
  {
    no: "7",
    field:
      "Expenditures for New Classroom Development Planning Consultants (RKB) Services at SMKN 1 PADAHERANG",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Veteran (Jalur 11) - AmlapuraJl. Dr. Radjiman No. 6 Bandung",
    numberDate: "117/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.246.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "8",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) at SMKN1 Cijulang",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "118/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.235.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "9",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) for SMKN 1 Kadipaten",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Tasikmalaya",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "116/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.224.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "10",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Study Services, Research and Technical Assistance",
    location: "Subang",
    name: "Department of Youth and Sports Tourism Subang",
    address: "Jl. A. Yani No.57 Pasirkareumbi",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "11",
    field:
      "Expenditures for Consultancy Services for Infrastructure Development Planning in Bogor (Package I)",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bogor",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/217- SPK/Konsul.Perenc/I nfrastruktur- Pkt.1/SMK/IV/2019 24/04/2019",
    value: "32.565.000",
    contract: "27/5/2019",
    handover: "28/5/2019",
  },
  {
    no: "12",
    field:
      "Expenditures for USB Development Planning Consultants at SMKN 1 Bungursari Purwakarta",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Purwakarta",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "13",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Ciamis",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
];

export default project2020;
