const project2021 = [
    {
      no: "1",
      field:
        "MRLL study on the Borobudur KSPN",
      subField: "Transportation",
      location: "Jakarta",
      name: "Ministry of Transportation Directorate General of Land Transportation",
      address: "Gedung Karya Jl. Merdeka Barat No.8 Jakarta",
      numberDate: "PL.107/215/2/SPK /SATKER- LLJ/VIII/2021 09/08/2021",
      value: "98.862.500",
      contract: "07/09/2021",
      handover: "07/09/2021",
    },
    {
      no: "2",
      field: "Preparation of Road and Bridge Priority Scale for the Gedebage Area",
      subField: "Road Civil",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34",
      numberDate: "027/01.0002/PL.0 6- Prc.SP.JJ./SPK/PPK M/DPU/2021 06/05/2021",
      value: "37.049.100",
      contract: "04/06/2021",
      handover: "04/06/2021",
    },
    {
      no: "3",
      field:
        "Consultancy Services for Study Room Rehabilitation at SMKN 1 Banjar, Banjar City",
      subField: "Architectural",
      location: "Banjar City",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3228/30.PRC.- REHAB.PSMK/DISD IK.KBR/2021 01/04/2021",
      value: "44.220.000",
      contract: "30/04/2021",
      handover: "30/04/2021",
    },
    {
      no: "4",
      field:
        "Study Room Rehabilitation Planning Consultancy Services SMKN 5 Kuningan Kab. Brass",
      subField: "Architecture",
      location: "Kuningan Regency",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3223/30.PRC.- REHAB.PSMK/DISD IK.JBR/2021 01/04/2021",
      value: "44.220.000",
      contract: "30/04/2021",
      handover: "30/04/2021",
    },
    {
      no: "5",
      field: "Creation of the INSW Integrated Control System",
      subField: "Telematics",
      location: "DKI Jakarta",
      name: "Ministry of Communication and Informatics",
      address: "Jl. Medan Merdeka Barat No.17, Jakarta",
      numberDate: "1630/PPK/KOMIN FO/DJ- SDPPI.4/08/2021 13/08/2021",
      value: "197.900.000",
      contract: "10/11/2021",
      handover: "10/11/2021",
    },
    {
      no: "6",
      field:
        "Review of Tegalwaru District Office Development Planning",
      subField: "Architecture",
      location: "Purwakarta Regency",
      name: "Office of Spatial Planning and Settlement of Purwakarta Regency",
      address: "Jl. KK Singawinata No. 116",
      numberDate: "601/12.SPK/Peren c.Pemb- Kec.Tegalwaru/Ta bang/V/2021 09/04/2021",
      value: "56.300.000",
      contract: "08/05/2021",
      handover: "08/05/2021",
    },
    {
      no: "7",
      field:
        "Population Data Synchronization With Other Ministries/Agencies",
      subField: "Telematics",
      location: "DKI Jakarta",
      name: "Ministry of Home Affairs of the Republic of Indonesia",
      address: "Jl. Raya Pasar Minggu Km.19 Jakarta Selatan",
      numberDate: "027/4844/PIAK.20 21 10/09/2021",
      value: "561.373.493",
      contract: "10/12/2021",
      handover: "10/12/2021",
    },
    {
      no: "8",
      field:
        "Engineering Planning for Sidewalk Development IV",
      subField: "Road Civil",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34",
      numberDate: "027/01.0002/PL.0 4- Prc.Pemb.Trot/SPK /PPKM/DPU/2021 14/09/2021",
      value: "45.595.000",
      contract: "13/10/2021",
      handover: "13/10/2021",
    },
    {
      no: "9",
      field:
        "Work on the Preparation of Technical Guidelines to Support the Food Security Program in the Lamunti Dadahup Area",
      subField: "Management",
      location: "Lamunti Dadahup area",
      name: "Directorate of Planning for the Realization of Transmigration Areas, Ministry of Villages",
      address: "Jln. TMP. Kalibata No. 17 Jakarta Selatan 12750",
      numberDate: "SPK.16/PPK-P2KT- PPKT/IX/2021 06/09/2021",
      value: "479.853.000",
      contract: "06/12/2021",
      handover: "06/12/2021",
    },
    {
      no: "10",
      field:
        "1 Provincial Management Consultant Jobs-4",
      subField: "Management",
      location: "West Java",
      name: "Department of Housing and Settlements Regional Government of West Java Province",
      address: "Jl. Kawaluyaan II No.4",
      numberDate: "03/SP/KMP4/2021 18/06/2021",
      value: "556.179.580",
      contract: "20/12/2021",
      handover: "20/12/2021",
    },
    {
      no: "11",
      field:
        "Compilation of the Study on the Development of the Padalarang Station TOD and the Impact of the Existence of the High Speed Train Station",
      subField: "Research Studies and Technical Assistance",
      location: "Padalarang",
      name: "Regional Research and Development Development Planning Agency ",
      address: "Perkantoran Pemkab Jl. Raya Padalarang-Cisarua Km.2 Ngamprah",
      numberDate: "027/1754/SPK/Ba ppelitbangda/202 1 15/11/2021",
      value: "97.372.000",
      contract: "14/12/2021",
      handover: "14/12/2021",
    },
    {
      no: "12",
      field:
        "Expenditures for USB Development Planning Consultants at SMKN 1 Bungursari Purwakarta",
      subField: "Research Studies and Technical Assistance",
      location: "Padalarang",
      name: "Regional Research and Development Development Planning Agency ",
      address: "Perkantoran Pemkab Jl. Raya Padalarang-Cisarua Km.2 Ngamprah",
      numberDate: "027/1787/SPK/Ba ppelitbangda/202 1 17/11/2021",
      value: "97.163.000",
      contract: "16/12/2021",
      handover: "16/12/2021",
    },
    {
      no: "13",
      field:
        "Research and Development Studies in the Health Sector (Epidemiological Surveillance in Purwakarta Regency)",
      subField: "Management",
      location: "Purwakarta Regency",
      name: "Regional Research and Development Planning Agency",
      address: "Jl. Gandanegara No.25",
      numberDate: "007/SPK-Kajian Kesehatan/XI/202 1 22/11/2021",
      value: "49.307.500",
      contract: "22/12/2021",
      handover: "16/12/2021",
    },
    {
      no: "14",
      field:
        "Review of Discipline Enforcement Technical Guidelines",
      subField: "Management",
      location: "Bogor City",
      name: "Bogor City Government BKPSDM Bogor City",
      address: "Jl. Julang 1 No.7 Bogor",
      numberDate: "027/09/DIS/MDK. D/SPK/IV/2021 20/04/2021",
      value: "57.200.000",
      contract: "18/06/2021",
      handover: "17/06/2021",
    },
    {
      no: "15",
      field:
        "Procurement of Planning Consultancy Services in the framework of Preparation of Landslide Disaster Management Plans",
      subField: "Management",
      location: "Sumedang Regency",
      name: "District Government Sumedang Regional Disaster Management Agency",
      address: "Jl. Empang No. 01",
      numberDate: "02.002/PPK/SP- RPBLONGSOR/BPB D/2021 26/02/2021",
      value: "94.323.515",
      contract: "27/03/2021",
      handover: "27/03/2021",
    },
    {
      no: "16",
      field:
        "Making Situation Map of Forest Area Boundary in Wlingi",
      subField: "Other Services/ Mapping",
      location: "East Java",
      name: "Ministry of Agrarian Affairs and Spatial Planning/National Land Agency Directorate General of Land and Spatial Surveys and Mapping",
      address: "Jl. Kuningan Barat I Nomor 1 Jakarta Selatan",
      numberDate: "172.4/SPMK/PPK- 5543/VI/2021 21/06/2021",
      value: "1.939.999.996",
      contract: "12/09/2021",
      handover: "03/09/2021",
    },
    {
      no: "17",
      field:
        "Making Situation Map of Forest Area Boundary in Yeh Leh Yeh Lebah and Budeng",
      subField: "Mapping",
      location: "Bali",
      name: "Ministry of Agrarian Affairs and Spatial Planning/National Land Agency",
      address: "Jl. Kuningan Barat 1 Nomor 1 Jakarta Selatan",
      numberDate: "139.4/KONTRAK/P PK-5543/V/2021 19/05/2021",
      value: "929.374.600",
      contract: "24/07/2021",
      handover: "11/08/2021",
    },
    {
      no: "18",
      field:
        "Inventory of Peat Ecosystem Characteristics in 4 Peat Hydrological Units (KHG) in West Kalimantan Province (Package V)",
      subField: "Other Services",
      location: "West Kalimantan",
      name: "Ministry of Environment and Forestry Directorate General of Pollution Control and Environmental Damage",
      address: "Jl. D.I. Panjaitan Kav.24 Kebon Nanas, Jakarta",
      numberDate: "SP-596/PPK-PKG/SMPEI- IFAD/07/2021 19/07/2021",
      value: "1.300.598.500",
      contract: "23/09/2021",
      handover: "05/10/2021",
    },
    {
      no: "19",
      field:
        "Tin Dome Mosque Design Conception Consultant",
      subField: "Architecture/Civil Building",
      location: "Pangkal Pinang City",
      name: "Department of Public Works and Spatial Planning",
      address: "Jl. Rasakunda Girimaya Pangkalpinang",
      numberDate: "15/SPK-KONSLT PMKT CK/APBDP/XI/202 102/11/2021",
      value: "94.890.000",
      contract: "30/12/2021",
      handover: "30/12/2021",
    },
    {
      no: "20",
      field:
        "Business Activity Data Updating Consultancy Services in Bogor City",
      subField: "Informatics Management",
      location: "Bogor City",
      name: "Bogor City Government Environment Service",
      address: "Jl. Paledang No.43 Kota Bogor",
      numberDate: "006/Kontrak/Kons. Upd.Data/TL/DLH/ III/2021 08/03/2021",
      value: "99.385.000",
      contract: "05/06/2021",
      handover: "03/06/2021",
    },
    {
      no: "21",
      field:
        "Jasa Konsultansi Perencanaan Pembangunan Ruang Praktek Sekolah (RPS) SMK PGRI Kab. Subang",
      subField: "Architecture",
      location: "Subang Regency",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3164/30.PRC.- RPS.PSMK/DISDIK. JBR/2021 02/02/2021",
      value: "44.154.000",
      contract: "03/03/2021",
      handover: "03/03/2021",
    },
    {
      no: "22",
      field:
        "Consultancy Services for Planning the Construction of School Practice Spaces (RPS) at SMKN 1 Binong Subang Regency",
      subField: "Architecture",
      location: "Subang Regency",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3165/30.PRC.- RPS.PSMK/DISDIK. JBR/2021 02/02/2021",
      value: "44.154.000",
      contract: "03/03/2021",
      handover: "03/03/2021",
    },
    {
      no: "23",
      field:
        "Making Situation Map of Forest Area Boundary in Wlingi",
      subField: "Architecture",
      location: "Subang Regency",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3163/30.PRC.- RPS.PSMK/DISDIK. JBR/2021 02/02/2021",
      value: "44.154.000",
      contract: "03/03/2021",
      handover: "03/03/2021",
    },
    {
      no: "24",
      field:
        "Consultant Services for Planning the Development of a High School Biology Laboratory Room, Kab. Cirebon, Kab. Karawang and Kab. Majalengka",
      subField: "Architecture",
      location: "West Java",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "027/830- SPK/Prc.Pembang unan/Disdik- PSMA/2021 28/05/2021",
      value: "90.966.000",
      contract: "17/06/2021",
      handover: "15/06/2021",
    },
    {
      no: "25",
      field:
        "Inventory of Peat Ecosystem Characteristics in 4 Peat Hydrological Units (KHG) in West Kalimantan Province (Package V)",
      subField: "Architecture",
      location: "West Java",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "027/490- SPK/Perencanaan. Pmb/Disdik- PSMA/2021 04/05/2021",
      value: "56.724.000",
      contract: "18/05/2021",
      handover: "18/05/2021",
    },
    {
      no: "26",
      field:
        "Service Room Rehabilitation Planning at 14 UPT Puskesmas (Cigarette Tax)",
      subField: "Civil Building",
      location: "Majalengka Regency",
      name: "Public Health Office",
      address: "Jl. Gerakan Koperasi No. 44 Majalengka",
      numberDate: "510.2/302/SPK/Ya nkes 14/06/2021",
      value: "70.015.000",
      contract: "28/07/2021",
      handover: "28/07/2021",
    },
    {
      no: "27",
      field:
        "Procurement of RAB and DED Planning Consultancy Services for the Cicinde Health Center",
      subField: "Architecture/Civil Building",
      location: "Karawang Regency",
      name: "Karawang District Health Office",
      address: "Jl. Parahiyangan No. 39 Karawang",
      numberDate: "01.02/04/SPK DED PKM CICINDE- DINKES/XII/2021 09/12/2021",
      value: "99.935.000",
      contract: "23/12/2021",
      handover: "21/12/2021",
    },
    {
      no: "28",
      field:
        "Procurement of RAB and DED Planning Consultancy Services for the Lemahduhur Health Center",
      subField: "Architecture/Civil Building",
      location: "Karawang Regency",
      name: "Karawang District Health Office",
      address: "Jl. Parahiyangan No. 39 Karawang",
      numberDate: "01.02/05/SPK DED PKM LEMAHDUHUR- DINKES/XII/2021 09/12/2021",
      value: "99.935.000",
      contract: "23/12/2021",
      handover: "21/12/2021",
    },
    {
      no: "29",
      field:
        "Procurement of RAB and DED Planning Consultancy Services for Pustu Sedari",
      subField: "Architecture/Civil Building",
      location: "Karawang Regency",
      name: "Karawang District Health Office",
      address: "Jl. Parahiyangan No. 39 Karawang",
      numberDate: "01.02/07/SPK DED PUSTI SEDARI- DINKES/XII/2021 09/12/2021",
      value: "19.965.000",
      contract: "23/12/2021",
      handover: "21/12/2021",
    },
    {
      no: "30",
      field:
        "Preparation of the 2021 General Investment Plan (RUPM).",
      subField: "Management",
      location: "Bandung Regency",
      name: "One Stop Investment and Services Office",
      address: "Jl. Raya Soreang Km. 17 Soreang",
      numberDate: "027/07/SPK/RUP M/DPMPTSP/2021 21/09/2021",
      value: "84.971.975",
      contract: "19/11/2021",
      handover: "19/11/2021",
    },
    {
      no: "31",
      field:
        "High School Classroom Rehabilitation Planning Consultant Services in Bekasi City",
      subField: "Architecture",
      location: "Bekasi City",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "027/683- SPK/Perencanaan. Rehab/Disdik- PSMA/2021 19/05/2021",
      value: "84.181.500",
      contract: "08/06/2021",
      handover: "04/06/2021",
    },
    {
      no: "32",
      field:
        "Preparation of Regional Scale Master Plan",
      subField: "Spatial Studies",
      location: "Bangka Regency",
      name: "Dinas Perumahan, Kawasan Permukiman dan Pertanahan",
      address: "Jl. Diponegoro No. 15 Sungailiat- Bangka",
      numberDate: "600/003/PPK/I- 0014/DINPERKPP/ 2021 01/04/2021",
      value: "99.789.800",
      contract: "30/05/2021",
      handover: "25/05/2021",
    },
    {
      no: "33",
      field:
        "Expenditures for Expert Services for Making Study of Folk Games in May",
      subField: "Research Studies and Technical Assistance",
      location: "Bandung City",
      name: "Bandung City Culture and Tourism Office",
      address: "Jl. Jend. Ahmad Yani No. 277 Bandung",
      numberDate: "027/527/03/PPK/ Disbudpar/2021 03/06/2021",
      value: "49.500.000",
      contract: "02/07/2021",
      handover: "02/07/2021",
    },
    {
      no: "34",
      field:
        "Survey and Preparation of 20 Literacy Signboard Geosite in Banten Province Activity: Establishment of Groundwater Conservation Zones in Deep Groundwater Basins",
      subField: "Survey Service",
      location: "Banten Province",
      name: "Office of Energy and Mineral Resources of Banten Province",
      address: "Jl. Syech Nawawi Al- Bantani (KP3B) Serang",
      numberDate: "027/33- 02.1.01.02- 6/KKT/PA/DESDM/ 2021 27/07/2021",
      value: "106.375.500",
      contract: "24/10/2021",
      handover: "24/10/2021",
    },
    {
      no: "35",
      field:
        "Detailed Engineering Design (DED) for the Development of Batu Lathe Tourism Object, Mekar Mukti Village, Waluran District",
      subField: "Architecture",
      location: "Sukabumi Regency",
      name: "Sukabumi District Tourism Office",
      address: "Jl. Jend. Sudirman, Jajaway",
      numberDate: "06/SPK-PPK/DED- Batububut/PARIWI SATA/APBD/2021 10/06/2021",
      value: "98.518.750",
      contract: "09/08/2021",
      handover: "09/08/2021",
    },
    {
      no: "36",
      field:
        "Detailed Engineering Design (DED) for the Development of Batu Lathe Tourism Object, Mekar Mukti Village, Waluran District",
      subField: "Architecture",
      location: "Sukabumi Regency",
      name: "Sukabumi District Tourism Office",
      address: "Jl. Jend. Sudirman, Jajaway",
      numberDate: "027017/16641609 -SPK/2021 22/03/2021",
      value: "99.343.750",
      contract: "21/05/2021",
      handover: "21/05/2021",
    },
    {
      no: "37",
      field:
        "SDA Planning VIII (Flood Control Planning)",
      subField: "Civil Water",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34 Bandung",
      numberDate: "027/01.0004/SPK- 18/PPKM/DPU/20 21 17/11/2021",
      value: "93.548.400",
      contract: "16/12/2021",
      handover: "16/12/2021",
    },
    {
      no: "38",
      field:
        "SDA Planning II (Flood Control Planning)",
      subField: "Civil Water",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34 Bandung",
      numberDate: "027/01.0004/SPK- 02/PPKM/DPU/20 21 16/04/2021",
      value: "78.842.280",
      contract: "14/06/2021",
      handover: "14/06/2021",
    },
    {
      no: "39",
      field:
        "Spatial Planning Information System",
      subField: "Telematics",
      location: "Bojonegoro Regency",
      name: "Office of Public Works, Highways and Spatial Planning Bojonegoro Regency",
      address: "Jl. Lettu Suyitno No. 39 Bojonegoro",
      numberDate: "650/007/SPK- JK.TR/APBD/412.2 03/2021 16/08/2021",
      value: "85.717.500",
      contract: "19/10/2021",
      handover: "19/10/2021",
    },
    {
      no: "40",
      field:
        "House Planning Consultancy Services Not Livable",
      subField: "Civil Building",
      location: "Depok City",
      name: "Government of Depok City, Cimanggis District",
      address: "Jl. Radar AURI No. 15 Cimanggis Depok",
      numberDate: "011/PPK- RTLH/PBJ/X/2021 01/10/2021",
      value: "189.893.000",
      contract: "29/11/2021",
      handover: "29/11/2021",
    },
    {
      no: "41",
      field:
        "Bekasi Regency Bridge Infrastructure Database",
      subField: "Telematics",
      location: "Bekasi Regency",
      name: "Department of Water Resources for Highways and Construction Development for Bekasi Regency",
      address: "Komp. Pemerintahan Kab. Bekasi Cikarang Pusat",
      numberDate: "602.3/282- LLG/SPP- PERTEK/PJT- DSDABMBK/2021 21/09/2021",
      value: "189.970.000",
      contract: "19/11/2021",
      handover: "19/11/2021",
    },
    {
      no: "42",
      field:
        "Planning for Collection of Livable and Uninhabitable Houses WP 2 in Kab. Bekasi",
      subField: "Telematics",
      location: "Bekasi Regency",
      name: "Department of Public Housing, Residential Areas and Land Affairs",
      address: "Komp. Pemerintahan Kab. Bekasi Cikarang Pusat",
      numberDate: "602.1/02.TND/2/S PP/PR/DISPERKINT AN/2021 09/09/2021",
      value: "348.359.000",
      contract: "07/12/2021",
      handover: "07/12/2021",
    },
    {
      no: "43",
      field:
        "APBD MBR Management Consulting Services",
      subField: "Management",
      location: "Lebak Regency",
      name: "Office of Public Housing and Slum Areas in the Regency/City of Lebak Regency",
      address: "Lebak Regency",
      numberDate: "027/85- SP/DPRKPP/VI/202 1 07/06/2021",
      value: "195.885.000",
      contract: "31/12/2021",
      handover: "31/12/2021",
    },
    {
      no: "44",
      field:
        "Preparation of UKL/UPL for the Port of Tanjung Pakuk",
      subField: "Environment",
      location: "Membalong Subdistrict",
      name: "Belitung Regency Transportation Service",
      address: "Jl. Anwar",
      numberDate: "04/SPK/UKLUPL- TGPAKUK/DISHUB /2021 28/07/2021",
      value: "237.490.000",
      contract: "24/11/2021",
      handover: "24/11/2021",
    },
    {
      no: "45",
      field:
        "Packaged Rural Clean Water Planning 03",
      subField: "Water Civil",
      location: "Bandung district",
      name: "Bandung Regency Government Office of Housing and Settlement Areas and Land Affairs",
      address: "Jl. Raya Soreang – Banjaran KM. 17",
      numberDate: "690/269/SPK/Prc.0 3/BIP/II/2021 15/02/2021",
      value: "99.070.400",
      contract: "31/03/2021",
      handover: "31/03/2021",
    },
    {
      no: "46",
      field:
        "Rural Clean Water Planning Package 10",
      subField: "Water Civil",
      location: "Bandung district",
      name: "Bandung Regency Government Office of Housing and Settlement Areas and Land Affairs",
      address: "Jl. Raya Soreang – Banjaran KM. 17",
      numberDate: "690/1195/SPK/Prc. 10/BIP/V/2021 03/05/2021",
      value: "99.181.500",
      contract: "16/06/2021",
      handover: "16/06/2021",
    },
    {
      no: "47",
      field:
        "Preparation of Zoning Regulations (PZ) for Rural Areas of Cijeunjing District",
      subField: "Study Services, Research and Technical Assistance",
      location: "Ciamis",
      name: "Department of Public Works, Spatial Planning and Land Affairs",
      address: "Jl. RAA. Sastrawinata No.1",
      numberDate: "027/66/PPK- CK/DPUPRP.4/202 1 18/06/2021",
      value: "71.540.000",
      contract: "15/09/2021",
      handover: "15/09/2021",
    },
    {
      no: "48",
      field:
        "Preparation of UKL - UPL Bakit Ferry Terminal",
      subField: "Environment",
      location: "Bangka Belitung Islands",
      name: "Bangka Belitung Islands Transportation Service",
      address: "comp. Integrated Offices and Residential Provincial Government Kep. Babel Air Itam Pangkalpinang",
      numberDate: "552/019/PBJ/TP- BAKIT_ASDP/DISH UB 16/11/2021",
      value: "98.890.000",
      contract: "28/12/2021",
      handover: "28/12/2021",
    },
    {
      no: "49",
      field:
        "Technical Planning for Package IV Irrigation Network Development",
      subField: "Environment",
      location: "West Bandung Regency",
      name: "Office of Public Works and Spatial Planning West Bandung Regency",
      address: "Jl. Raya Padalarang – Cisarua Km. 2 Mekarsari Ngamprah Bandung Barat",
      numberDate: "602.2/SP/PJI.04/B SDA/IX/2021 21/09/2021",
      value: "98.604.000",
      contract: "19/11/2021",
      handover: "19/11/2021",
    },
  ];
  
  export default project2021;
  