const project2018 = [
  {
    no: "1",
    field:
      "Monitoring Well Development Planning Consultancy",
    subField: "Water Civil Engineering Planning",
    location: "Bekasi City",
    name: "Bekasi City Environmental Service",
    address: "Jl. Jend. A. Yani No. 1",
    numberDate: "027/04-DED SUMUR/DinasLH.PPKL H 31-08-2018",
    value: "162.000.000",
    contract: "14/10/2018",
    handover: "14/10/2018",
  },
  {
    no: "2",
    field: "Data Center & Command Center Building Consultancy Services Kab. Tanah Laut Regency",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Tanah Laut Regency",
    name: "Diskominfo",
    address: "Jl. A. Syairani Komp. Perkantoran Pelaihari",
    numberDate: "027/10/SPK/PL/DISKO MINFO/2018 12/11/2018",
    value: "59.400.000",
    contract: "15/12/2018",
    handover: "15/12/2018",
  },
  {
    no: "3",
    field:
      "DED Drainage Channel Jl. Jakarta-Jl. Kiaracondong",
    subField: "Water Civil Engineering Planning",
    location: "Bandung City",
    name: "Bandung City Public Works Department",
    address: "Jl. Cianjur No. 34 Bandung",
    numberDate: "027/37.03/PL.03/SPK /PPKm/DPU/2018 9/10/2018",
    value: "48.785.000",
    contract: "7/11/2018",
    handover: "7/11/2018",
  },
  {
    no: "4",
    field:
      "Preparation of District Environmental Quality Index. East Belitung",
    subField: "Study Services. Research and Engineering/Environmental Assistance",
    location: "East Belitung Regency",
    name: "District Environmental Service. East Belitung",
    address: "Jl. Raya Manggar- Gantung Dusun Manggarawan Manggar",
    numberDate: "01/SPK/KONS- IKLH/DLH/2018 6/9/2018",
    value: "49.500.000",
    contract: "5/11/2018",
    handover: "31/10/2018",
  },
  {
    no: "5",
    field: "Study of the Potential of Construction Experts",
    subField: "Study Services. Research and Technical Assistance",
    location: "Banten Province",
    name: "Banten Province PUPR Service",
    address: "Jl. Syeh Nawawi Al Bantani Kota Serang Banten",
    numberDate: "900/187/SPK/BJK/DP UPR/X/2018 15/10/2018",
    value: "93.520.000",
    contract: "13/12/2018",
    handover: "13/12/2018",
  },
  {
    no: "6",
    field:
      "Preparation of Reservoir Management and Conservation Profiles. Embung. Sites and other water storage buildings",
    subField: "Water Civil Engineering Planning",
    location: "Banten Province",
    name: "Banten Province PUPR Service",
    address: "Jl. Syeh Nawawi Al Bantani Kota Serang Banten",
    numberDate: "900/SP.46.4.9/PJSA- DPUPR/2018 15/11/2018",
    value: "36.490.000",
    contract: "14/12/2018",
    handover: "7/11/2018",
  },
  {
    no: "7",
    field:
      "Shopping Print Activities for Preparing Guidebooks for Giving Awards for West Java Youth",
    subField: "Other Services",
    location: "West Java Province",
    name: "Provincial Youth and Sports Department. West Java",
    address: "Jl. Pacuan Kuda No. 140 Arcamanik. Bandung",
    numberDate: "27/SP/Sarpras Kesejahteraan/2018 28/11/2018",
    value: "18.100.000",
    contract: "12/12/2018",
    handover: "12/12/2018",
  },
  {
    no: "8",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Sukamaju District. Ds Warga Jaya and Ds Rengasjajar District. Cigudeg",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0028/SPK/AM- PL/PUPR/2018 2/11/2018",
    value: "28.935.000",
    contract: "26/11/2018",
    handover: "26/11/2018",
  },
  {
    no: "9",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Rabak (Kp. Rabak) Kec. Rumpin",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0027/SPK/AM- PL/PUPR/2018 31/10/2018",
    value: "9.355.000",
    contract: "24/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "10",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Jasinga District. Jasinga",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0030/SPK/AM- PL/PUPR/2018 1/11/2018",
    value: "9.355.000",
    contract: "25/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "11",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Malasari & Ds Curug Bitung District. Bear it",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0008/SPK/AM- PL/PUPR/2018 31/10/2018",
    value: "25.594.000",
    contract: "24/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "12",
    field:
      "SPAM Development Planning in Ds. Kiarasari. Etc. Sukamulih. & Etc. Sukajaya District. Sukajaya",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.03- 30.0005/SPK/AM- PL/PUPR/2018 2/11/2018",
    value: "42.645.000",
    contract: "26/11/2018",
    handover: "26/11/2018",
  },
  {
    no: "13",
    field:
      "Preparation of FS and DED for Small Scale Business Activities in the Kapuas Watershed",
    subField: "Study Services. Research and Technical Assistance",
    location: "Ministry of Environment & Forestry",
    name: "DIRECTOR GENERAL of Environmental Damage and Control",
    address: "Jl. D.I. Panjaitan Kav. 24. Kebon Nanas. Jakarta",
    numberDate: "SPK-1056/PPA/PPK- LU/2018 12/10/2018",
    value: "99.770.000",
    contract: "10/12/2018",
    handover: "10/12/2018",
  },
  {
    no: "14",
    field:
      "Data collection and preparation of a normative list of residents for land control within ROW boundaries for the construction of a double track railway between Bogor - Batutulis",
    subField: "Survey",
    location: "Ministry of Transportation",
    name: "DIRECTOR GENERAL of Railways",
    address: "Jl. Raya Gedebage No. 68 Bandung",
    numberDate: "PL.202/04/02/PPK- PP/BTKA- JABAR/PNTN/X-18 1/10/2018",
    value: "195.210.000",
    contract: "29/11/2018",
    handover: "1/12/2018",
  },
  {
    no: "15",
    field:
      "Preliminary Survey and Technical Coordination for the Implementation of the Kulon Progo Airport Public Train using the PPP Scheme",
    subField: "Survey",
    location: "Ministry of Transportation",
    name: "DIRECTOR GENERAL of Railways",
    address: "Graha Jatibaru Blok C-7 Jl. Jatibaru Timur No. 56A Cideng- Jakarta",
    numberDate: "03/JL- PDK/LLA.KA/XI/2018 30/11/2018",
    value: "176.209.000",
    contract: "31/12/2018",
    handover: "31/12/2018",
  },
  {
    no: "16",
    field:
      "Cijerah Community Health Center Planning Consultant - Cijerah Community Health Center Development Planning Consultant",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bandung City",
    name: "Bandung City Health Department",
    address: "Jl. Citarum No. 34 Bandung",
    numberDate: "027/090.09/PPK.B- Dinkes/2018 17/09/2018",
    value: "98.560.000",
    contract: "15/11/2018",
    handover: "15/11/2018",
  },
  {
    no: "17",
    field:
      "Musrenbang TA Road Rehab/Maintenance Technical Planning. 2018 Margahayu Region",
    subField: "Transportation Civil Engineering",
    location: "Bandung district",
    name: "District Public Works & Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang Banjaran KM.3 Soreang",
    numberDate: "602.1/9/KTR/P.18.01. JKP.09/DPUPR/2018 1/2/2018",
    value: "49.770.000",
    contract: "19/03/2018",
    handover: "19/03/2018",
  },
  {
    no: "18",
    field:
      "Technical Planning for Rehab/Maintenance of Roads in the Cileunyi Region (2019 DAK Proposal)",
    subField: "Transportation Civil Engineering",
    location: "Bandung district",
    name: "District Public Works & Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang Banjaran KM.3 Soreang",
    numberDate: "602.1/20/KTR/P.18.0 1.JKP.20/DPUPR/2018 16/05/2018",
    value: "49.750.000",
    contract: "29/06/2018",
    handover: "29/06/2018",
  },
  {
    no: "19",
    field:
      "BANGUB 2019 Proposed Road Rehab/Maintenance Technical Planning for Region 1",
    subField: "Transportation Civil Engineering",
    location: "Bandung district",
    name: "District Public Works & Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang Banjaran KM.3 Soreang",
    numberDate: "602.1/38/KTR/P.18.0 1.JKP.38/DPUPR/2018 12/7/2018",
    value: "49.735.000",
    contract: "26/08/2018",
    handover: "24/08/2018",
  },
  {
    no: "20",
    field:
      "DED Widening of UNSIKA Side Bridge",
    subField: "Transportation Civil Engineering",
    location: "Karawang District",
    name: "District Public Works & Spatial Planning Department. Karawang",
    address: "Jl. Dewi Sartika No. 01 Karawang",
    numberDate: "027/13/SP/PUPR/JKS- 9/X/2018 19/9/2018",
    value: "97.350.000",
    contract: "18/11/2018",
    handover: "18/11/2018",
  },
  {
    no: "21",
    field:
      "DED Inventory of Cikampek City Drainage Channels",
    subField: "Transportation Civil Engineering",
    location: "Karawang District",
    name: "District Public Works & Spatial Planning Department. Karawang",
    address: "Jl. Dewi Sartika No. 01 Karawang",
    numberDate: "027/12/SP/PUPR/JKS- 9/X/2018 19/9/2018",
    value: "98.450.000",
    contract: "18/11/2018",
    handover: "18/11/2018",
  },
  {
    no: "22",
    field:
      "Preparation of the DED for Restructuring Areas and Infrastructure in Former Mining Areas in Tanah Bumbu Regency, Province. South Kalimantan",
    subField: "Regional Planning / Spatial Planning",
    location: "Tanah Bumbu Regency",
    name: "PT. SURYA BERSAUDARA",
    address: "Jl. H. Agus Salim No. 18 Kotabaru",
    numberDate: "06/PT.SB-KTB/X/2018 17/10/2018",
    value: "1.023.800.000",
    contract: "18/12/2018",
    handover: "18/12/2018",
  },
  {
    no: "23",
    field:
      "Environmental Road Planning. Package 1",
    subField: "Transportation Civil Engineering",
    location: "Bandung Regency",
    name: "Public Housing Department. Residential and Land Areas",
    address: "Komplek Pemda Jl. Raya Soreang KM.17",
    numberDate: "663/12/SPK/PRC.JALI NK.1/X/2018 29/10/2018",
    value: "96.635.000",
    contract: "27/11/2018",
    handover: "27/11/2018",
  },
  {
    no: "24",
    field:
      "Planning/DED Services Renovation of PT Employee Dormitory Building. Coats Rejo Indonesia",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bogor",
    name: "PT. Coats Rejo Indonesia",
    address: "Jl. Raya Tajur No.24 Bogor",
    numberDate: "026/PUR/CRI/DED- ENG/2018 10/08/2018",
    value: "805.610.000",
    contract: "11/11/2018",
    handover: "11/11/2018",
  },
  {
    no: "25",
    field:
      "DED Technical Planning Consultancy Services for Outpatient Installation Building Construction",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Majalengka District",
    name: "Cideres Regional General Hospital",
    address: "Jl. Raya Cideres- Kadipaten No. 180",
    numberDate: "671/022/SP- DED/RSUD- CIDERES/2018 23/10/2018",
    value: "204.250.000",
    contract: "24/12/2018",
    handover: "24/12/2018",
  },
  {
    no: "26",
    field:
      "Feasibility Study (FS) Planning and Environmental Management Efforts (UKL) and Environmental Monitoring Efforts (UPL)",
    subField: "Environment",
    location: "Kotabaru",
    name: "PT. Surya Bersaudara",
    address: "Jl. H. Agus Salim No. 18 Kotabaru",
    numberDate: "02/PT.SB- KTB/VII/2018 13/07/2018",
    value: "615.800.000",
    contract: "14/09/2018",
    handover: "14/09/2018",
  },
  {
    no: "27",
    field:
      "Evaluation of KLHS and RDTR in Urban Areas",
    subField: "Regional Planning / Spatial Planning",
    location: "Boalemo Regency",
    name: "District Public Works Department. Boalemo",
    address: "Jl. Siti Rawi No. 1 Limbato Tilamuta",
    numberDate: "619/KONTRAK/PU/KL HS/09/VII/2018 11-07-2018",
    value: "200.410.000",
    contract: "12/10/2018",
    handover: "12/10/2018",
  },
  {
    no: "28",
    field:
      "Review of Master Plan and Waste Water Management System Development Planning (SPAL)",
    subField: "Water Civil Engineering Planning",
    location: "Palembang",
    name: "PT. Semen Baturaja Palembang",
    address: "Jl. Abikusno Cokrosuyoso Kertapati Palembang",
    numberDate: "HK.00.09/214/2018 17/09/2018",
    value: "510.200.000",
    contract: "19/12/2018",
    handover: "19/12/2018",
  },
  {
    no: "29",
    field:
      "Peatland Inventory Study on the West Aceh - Aceh Jaya Border and Preparation of FS Land Reclamation Plan",
    subField: "Other Services / Survey / Mapping",
    location: "West Aceh District- Aceh Jaya",
    name: "PT. Mifa Bersaudara",
    address: "Jl. Imam Bonjol No. 45 Dusun Cot Gampong, Kabupaten Aceh Barat",
    numberDate: "016/MIFA- GSP/PERJ/VII/2018 27-07-2018",
    value: "1.058.500.000",
    contract: "07-01-2019",
    handover: "07-01-2019",
  },
];

export default project2018;
