const project2015 = [
  {
    no: "1",
    field:
      "Urban Drainage Planning, Bakti Jaya Village, Setu District",
    subField: "Water Civil Engineering Planning",
    location: "South Tangerang City",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong No. 01 Kav.51B Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/1- 013/DBMSDA/III/201 54/3/2015",
    value: "48.790.000",
    contract: "2/4/2015",
    handover: "2/4/2015",
  },
  {
    no: "2",
    field: "Urban Drainage Planning for Kademangan Village, Setu District",
    subField: "Water Civil Engineering Planning",
    location: "Tanah Laut Regency",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong No. 01 Kav.51B Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/1- 014/DBMSDA/III/201 54/3/2015",
    value: "48.790.000",
    contract: "2/4/2015",
    handover: "2/4/2015",
  },
  {
    no: "3",
    field:
      "Expenditures on Aerial Mapping Services for Making Basic Maps at a Scale of 1:5,000 Orthorectification and Sectoral Data",
    subField: "Survey Services / Map Making Services",
    location: "Subang Regency",
    name: "District Settlement Spatial Planning and Cleanliness Service. Subang",
    address: "Jl. K.S. Tubun No. 16 Kab. Subang",
    numberDate: "027/911/SP.PPK- PETA/DISTARKIMSIH 28-7-2015",
    value: "560.970.000",
    contract: "27/11/2015",
    handover: "30/11/2015",
  },
  {
    no: "4",
    field:
      "Consultancy Services for Preparing DED for Sports Fields. Parking lot. Pedestrian and Green Open Space (RTH)",
    subField: "Building and Landscape Environmental Design",
    location: "Subang Regency",
    name: "Subang Regency Social Service",
    address: "Jl. D.I. Panjaitan No. 81. Kab. Subang",
    numberDate: "027/643/Umum 3/6/2015",
    value: "205.130.000",
    contract: "4/9/2015",
    handover: "4/9/2015",
  },
  {
    no: "5",
    field: "Preparation of Technical Guidelines for Reclamation and Post-Mining Guarantees",
    subField: "Study, Research and Technical Assistance Services",
    location: "Lingga Regency",
    name: "Department of Mining and Energy District",
    address: "Jl. Istana Kota Baru. Daik Linga",
    numberDate: "11/SP/PPK/DPE-RPT/ APBD/VIII/2015 10/8/2015",
    value: "165.800.000",
    contract: "9/11/2015",
    handover: "9/11/2015",
  },
  {
    no: "6",
    field:
      "Creation of Disaster Monitoring and Reporting Applications",
    subField: "Telematics",
    location: "Bandung Regency",
    name: "BPBD Bandung Regency",
    address: "Jln. Raya Soreang KM 17 Soreang. Kab. Bandung",
    numberDate: "027/81/SP.KONTRAK/ SIM/VI/2015 3/6/2015",
    value: "178.500.000",
    contract: "2/9/2015",
    handover: "2/9/2015",
  },
  {
    no: "7",
    field:
      "Manual preparation of OP Raw water",
    subField: "Water Civil Engineering Planning",
    location: "Manado City",
    name: "Kemen PU - Dirjen Cipta Karya",
    address: "Jl. Tikala Ares No. 80 Manado",
    numberDate: "19/SP- KONS/PPLP/2015 17-06-2015",
    value: "250.850.000",
    contract: "18/09/2015",
    handover: "18/09/2015",
  },
  {
    no: "8",
    field:
      "Preparation of a Waste Master Plan",
    subField: "Study, Research and Technical Assistance Services",
    location: "Padang Pariaman Regency",
    name: "Public Works Service",
    address: "Jl. Jambak – Ketapang KM 01 Kebun Baru Kec. Lubuk Alung",
    numberDate: "70/SP-DPU/VII-2015 9/7/2015",
    value: "303.100.000",
    contract: "10/10/2015",
    handover: "9/10/2015",
  },
  {
    no: "9",
    field:
      "Development of GIS Applications for Ground Water Management",
    subField: "Telematics",
    location: "Tapin Regency",
    name: "Tapin Regency Mining and Energy Service",
    address: "Jl. Jend. Sudirman (By Pass) No. 14 Rantau",
    numberDate: "540/73/DISTAMBEN/ 2015 16-10-2015",
    value: "174.500.000",
    contract: "17/12/2015",
    handover: "17/12/2015",
  },
  {
    no: "10",
    field:
      "Buol Regency Road and Bridge GIS Mapping Consultancy Services",
    subField: "Survey Service",
    location: "Buol Regency",
    name: "Buol Regency Public Works Department",
    address: "Jl. Batalipu No. 9 Kec. Biau Buol",
    numberDate: "640/38.b.09/AB/CK.P U/2015 17-9-2015",
    value: "246.230.000",
    contract: "19/12/2015",
    handover: "21/12/2015",
  },
  {
    no: "11",
    field:
      "Preparation of DED for Swamp Management District. Indragiri Hilir",
    subField: "Water Civil Engineering Planning",
    location: "Indragiri Hilir Distict",
    name: "Department of Human Settlements & Public Housing",
    address: "Jl. Ki Hajar Dewantara No. 1. Tembilahan",
    numberDate: "647/DCKPERA/SP/KPK /V/2015 4/5/2015",
    value: "212.000.000",
    contract: "5/8/2015",
    handover: "5/8/2015",
  },
  {
    no: "12",
    field:
      "Feasibility Study and Terminal Traffic Impact Analysis",
    subField: "Transportation Civil Engineering Planning",
    location: "North Maluku Province",
    name: "Department of Transportation. Communication and Informatics North Maluku Province",
    address: "Jl. Raya Lintas Halmahera Gosale Puncak Sofifi",
    numberDate: "550/11/SPP/FS- ANDAL/DPKI/MU/2015 13/07/2015",
    value: "420.120.000",
    contract: "13/11/2015",
    handover: "13/11/2015",
  },
  {
    no: "13",
    field:
      "Technical Planning for the Development of Clean Water Facilities and Infrastructure",
    subField: "Water Civil Engineering Planning",
    location: "Banjar City",
    name: "Department of Human Settlements. Cleanliness. Spatial Planning and Environment",
    address: "Jl. Tentara Pelajar No.437",
    numberDate: "602.21/08.SPK/17- PRC.TR.01/PPK.EKW 16/07/2015",
    value: "210.200.000",
    contract: "17/10/2015",
    handover: "19/10/2015",
  },
  {
    no: "14",
    field:
      "Institutional Study of the Management of the Drinking Water Management System (SPAM) of East Kutai Regency",
    subField: "Water Civil Engineering Planning",
    location: "East Kutai Regency",
    name: "East Kutai Regency Public Works Department",
    address: "Kawasan Pusat Pemerintahan Bukit Pelangi Sangatta",
    numberDate: "600/14.KONTRAK/RE NC-18/DPU- CK/VI/2015 22/06/2015",
    value: "282.120.000",
    contract: "21/10/2015",
    handover: "21/10/2015",
  },
  {
    no: "15",
    field:
      "DED Leger Planning for East Kutai Regency Road",
    subField: "East Kutai Regency",
    location: "Ministry of Transportation",
    name: "East Kutai Regency Public Works Department",
    address: "Kawasan Pusat Pemerintahan Bukit Pelangi Sangatta",
    numberDate: "600/14.KONTRAK/RE NC-18/DPU- CK/VIII/2015 19-08-2015",
    value: "197.350.000",
    contract: "20/11/2015",
    handover: "20/11/2015",
  },
  {
    no: "16",
    field:
      "Planning Services/Preparation of Master Plan for Development of Dr. RSUD. Slamet",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Garut District",
    name: "Regional General Hospital dr. Slamet Garut Regency Government",
    address: "Jl. Rumah Sakit No. 12",
    numberDate: "12.2/PPK/SP/RSU/III/ 2015 16-03-2015",
    value: "190.100.000",
    contract: "15/05/2015",
    handover: "15/05/2015",
  },
];

export default project2015;
