const project2017 = [
  {
    no: "1",
    field:
      "Environmental Road Maintenance Planning. People and channels in Pasar Minggu District",
    subField: "Environment",
    location: "DKI Jakarta Province",
    name: "Provincial Highways Department. DKI Jakarta",
    address: "Jl. Prapanca Raya No.09 Blok. C Lt.VII Kebayoran Baru Jakarta",
    numberDate: "2330/-1.793.2 /2017 3/4/2017",
    value: "43.186.000",
    contract: "30/04/2017",
    handover: "30/04/2017",
  },
  {
    no: "2",
    field: "Planning (Planning) for the Construction of Sidewalks and Road Complementary Buildings in Pasar Minggu District",
    subField: "Building and Landscape Environmental Design",
    location: "DKI Jakarta Province",
    name: "Provincial Highways Department. DKI Jakarta",
    address: "Jl. Prapanca Raya No.09 Blok. C Lt.VII Kebayoran Baru Jakarta",
    numberDate: "1149/-1.792.3 /2017 01/03/2017",
    value: "43.241.000",
    contract: "28/03/2017",
    handover: "28/03/2017",
  },
  {
    no: "3",
    field:
      "Children's Playground Arrangement Planning (In Front of the Regional Secretary's House)",
    subField: "Building and Landscape Environmental Design",
    location: "Bandung District",
    name: "Department of Public Housing, Settlement Areas and Land, Bandung Regency",
    address: "Jl. Raya Soreang KM. 17 Soreang",
    numberDate: "602.21/54.a/SPK/PE RC.TMN/BID.PP/DIS P/VI/ 2017 05/06/2017",
    value: "19.690.000",
    contract: "04/07/2017",
    handover: "04/07/2017",
  },
  {
    no: "4",
    field:
      "Building Data Collection Work in South Cimahi District",
    subField: "Survey",
    location: "Cimahi City",
    name: "Cimahi City Public Works and Spatial Planning Department",
    address: "Jl. Rd. Hardja kusumah Blok Jati Cihanjuang Cimahi",
    numberDate: "03/PPK/SPK/PRC.AB T-Monev- 4/TBJK.DPU PR/2017 13/11/2017",
    value: "46.585.000",
    contract: "27/12/2017",
    handover: "27/12/2017",
  },
  {
    no: "5",
    field: "Survey & Mapping of Rice Field Expansion Design",
    subField: "Survey / Mapping",
    location: "Regency. Upper South River",
    name: "Department of Agriculture, Food Crops & Horticulture",
    address: "Jl. Jend. A. Yani No. 09 Kandangan",
    numberDate: "521.3/07/SP/PPK/S PDPS/DistanTPH/20 17 01/09/2017",
    value: "316.915.000",
    contract: "1/12/2017",
    handover: "1/12/2017",
  },
  {
    no: "6",
    field:
      "Space Utilization Mapping Consultancy Services",
    subField: "Telematic / Mapping",
    location: "Kutai Kertanegara Regency",
    name: "Department of Human Settlements & Spatial Planning",
    address: "Jl. Jend. A. Yani",
    numberDate: "217-800/CK- TR/VI/2017 29/06/2017",
    value: "192.500.000",
    contract: "30/09/2017",
    handover: "2/10/2017",
  },
  {
    no: "7",
    field:
      "Detailed Engineering Design (DED) Clean Water Planning",
    subField: "Water Civil Engineering Planning",
    location: "Donggala Regency",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Pue Mami No. 01",
    numberDate: "660.06/KONT.DED/ DPUPR/KAB.DGL/VII /2017 12/07/2017",
    value: "315.840.000",
    contract: "11/10/2017",
    handover: "11/10/2017",
  },
  {
    no: "8",
    field:
      "Planning for the Development of a Clean Water Treatment System Installation in the PT Factory Environment. Semen Baturaja (Persero) Tbk.",
    subField: "Water / Environmental Civil Engineering Planning",
    location: "Palembang",
    name: "PT. Semen Baturaja Palembang",
    address: "Jl. Abikusno Cokrosuyoso Kertapati Palembang",
    numberDate: "HK.00.08/227/2017 07/08/2017",
    value: "450.250.000",
    contract: "8/11/2017",
    handover: "8/11/2017",
  },
  {
    no: "9",
    field:
      "Technical Planning for Renovation of Ex. Office Building. DBMSDA",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pandeglang Regency",
    name: "District Public Works and Spatial Planning Department. Pandeglang",
    address: "Jl. Jend. Sudirman. Cikupa Pandeglang",
    numberDate: "640/08/SPK.ELANG/ PPK.PB/DPUPR/201 7 12/06/2017",
    value: "130.581.000",
    contract: "09/09/2017",
    handover: "09/09/2017",
  },
  {
    no: "10",
    field:
      "Planning for the Room Arrangement of the Sukabumi Regency DPRD Building",
    subField: "Architectural Planning",
    location: "Sukabumi Regency",
    name: "Sukabumi Regency Council Secretariat",
    address: "Jl. Jend. Sudirman. Sukabumi",
    numberDate: "027/383.1/SETWAN 04/05/2017",
    value: "148.912.000",
    contract: "18/06/2017",
    handover: "18/06/2017",
  },
  {
    no: "11",
    field:
      "DED Planning Consultant Services for Radiology and Laboratory Buildings",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Sukabumi District",
    name: "BLUD Sekarwangi Hospital District. Sukabumi",
    address: "Jl. Siliwangi No.49",
    numberDate: "027/11/PPK/DED- GRL/07/2017 17/07/2017",
    value: "277.400.000",
    contract: "18/09/2017",
    handover: "18/09/2017",
  },
];

export default project2017;
