const project2016 = [
  {
    no: "1",
    field:
      "Urban Drainage Channel Planning for Sawah Village, Ciputat District",
    subField: "Water Civil Engineering Planning",
    location: "South Tangerang City",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/ 1-017/ DBMSDA/IX/2016 20/09/2016",
    value: "36.707.000",
    contract: "18/11/2016",
    handover: "18/11/2016",
  },
  {
    no: "2",
    field: "Urban Drainage Channel Planning, Jombang Village, Ciputat District",
    subField: "Water Civil Engineering Planning",
    location: "South Tangerang City",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/ 1-019/ DBMSDA/IX/2016 20/09/2016",
    value: "36.707.000",
    contract: "18/11/2016",
    handover: "18/11/2016",
  },
  {
    no: "3",
    field:
      "Urban Drainage Channel Planning for Sawah Baru Village, Ciputat District",
    subField: "Water Civil Engineering Planning",
    location: "South Tangerang City",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/ 1-018/ DBMSDA/IX/2016 20/09/2016",
    value: "36.707.000",
    contract: "18/11/2016",
    handover: "18/11/2016",
  },
  {
    no: "4",
    field:
      "Urban Drainage Channel Planning for Serua Village, Ciputat District",
    subField: "Water Civil Engineering Planning",
    location: "South Tangerang City",
    name: "South Tangerang City Highways and Water Resources Department",
    address: "Jl. Raya Puspiptek Serpong Tangerang Selatan",
    numberDate: "027.1/PRCDRALINK/ 1-020/ DBMSDA/IX/2016 20/09/2016",
    value: "36.707.000",
    contract: "18/11/2016",
    handover: "18/11/2016",
  },
  {
    no: "5",
    field: "Work on Preparing the Draft Regional Regulation on PSU (Infrastructure, Facilities and Utilities)",
    subField: "Research Studies and Technical Assistance",
    location: "Regency. Indragiri Hilir",
    name: "Department of Human Settlements and Public Housing District. Indragiri Hilir",
    address: "Jl. Ki Hajar Dewantara No. 01 Tembilahan",
    numberDate: "650/DCKPERA/SP/K PK/VII/2016/03.11 21-7-2016",
    value: "142.100.000",
    contract: "23/10/2016",
    handover: "24/10/2016",
  },
  {
    no: "6",
    field:
      "Cipatat District DED CAP-RPP Planning",
    subField: "Regional Planning / Spatial Planning",
    location: "West Bandung Regency",
    name: "Department of Human Settlements and Spatial Planning, West Bandung Regency",
    address: "Jl. Raya Padalarang- Cisarua KM.02 KBB",
    numberDate: "648/05/SPK/DED.C AP/CPT/DCKTR/III/1 61/3/2016",
    value: "49.368.000",
    contract: "29/04/2016",
    handover: "29/04/2016",
  },
  {
    no: "7",
    field:
      "DED CAP-RPP Planning Consultancy Services",
    subField: "Regional Planning / Spatial Planning",
    location: "West Bandung Regency",
    name: "Department of Human Settlements and Spatial Planning, West Bandung Regency",
    address: "Jl. Raya Padalarang- Cisarua KM.02 KBB",
    numberDate: "648/05/SPK/DED.C AP/RG/DCKTR/X/20 16 27-10-2016",
    value: "49.445.000",
    contract: "27/12/2016",
    handover: "23/12/2016",
  },
  {
    no: "8",
    field:
      "Planning for Environmental Arrangement of Parks and Paving Blocks",
    subField: "Building and Landscape Environmental Design",
    location: "Bandung Regency",
    name: "Bandung Regency Government Education and Culture Service",
    address: "Jl. Raya Soreang Km.17",
    numberDate: "641/14/SPK/PRC.PV B/IV/2016 04/04/2016",
    value: "14.924.000",
    contract: "18/04/2016",
    handover: "18/04/2016",
  },
  {
    no: "9",
    field:
      "Making Detailed Engineering Design (Detailed Technical Design) of Medical Waste Management Facilities",
    subField: "Environmental",
    location: "Bontang City",
    name: "Bontang Health Department",
    address: "Jl. A. Yani RT.11 No.1",
    numberDate: "421/10/Pusk/Pan.P eng-Diskes 17-10-2016",
    value: "181.500.000",
    contract: "17/10/2016",
    handover: "16/12/2016",
  },
  {
    no: "10",
    field:
      "Sarolangun IUP Mining Area Boundary Measuring and Mapping Services",
    subField: "Survey / Mapping",
    location: "Palembang",
    name: "PT. Semen Baturaja (Persero) Tbk Palembang",
    address: "Jl. Abikusno Cokrosuyoso, Kertapati, Palembang",
    numberDate: "HK.00.09/215/2016 08/08/2016",
    value: "1.350.250.000",
    contract: "08/11/2016",
    handover: "08/11/2016",
  },
  {
    no: "11",
    field:
      "DED Consultancy Services for ICU Room Construction. HCU. CSSD. UPT RSUD Nutrition Installation",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran Regency",
    name: "District Health Department. Pangandaran",
    address: "Jl. Pasundan No. 42 Cijulang",
    numberDate: "027/1224/PPK.01/U M.Dinkes/2016 16/06/2016",
    value: "184.750.000",
    contract: "18/08/2016",
    handover: "19/08/2016",
  },
];

export default project2016;
