const project2019 = [
  {
    no: "1",
    field:
      "Preparation of Regional Action Plans (RAD) Activities of Disaster Management Plans (RPB)",
    subField: "Study Services, Research and Technical Assistance",
    location: "Sumedang District",
    name: "Regional Disaster Management Agency (BPBD)",
    address: "Jl. Empang No. 01 Sumedang 45312",
    numberDate: "02.1/SPK/RAD/BPBD /2019 5/3/2019",
    value: "90.948.000",
    contract: "3/4/2019",
    handover: "3/4/2019",
  },
  {
    no: "2",
    field: "Pedestrian Bridge Planning Consultant Services",
    subField: "Transportation Civil Engineering Engineering",
    location: "Bandung City",
    name: "Bandung City Department of Transportation",
    address: "Jl. Soekarno Hatta No.205",
    numberDate: "03/PPK-PPSTK- PPJPO/II/DISHUB/20 19 12/2/2019",
    value: "98.395.000",
    contract: "12/4/2019",
    handover: "12/4/2019",
  },
  {
    no: "3",
    field:
      "Consultancy Services for Heavy Rehabilitation Planning of SDN Tanjung Priok Building 02/03",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "DKI Jakarta",
    name: "Region I Education Office North Jakarta Administrative City",
    address: "Jl. Laksda Yos Sudarso No.27-29",
    numberDate: "463/1.851.2.061 12/2/2019",
    value: "76.700.000",
    contract: "13/03/2019",
    handover: "13/03/2019",
  },
  {
    no: "4",
    field:
      "Preparation of DED for the Development of the Senopati & Bendungan Hilir Waste Water Pipeline Network",
    subField: "Water Civil Engineering Engineering",
    location: "South Jakarta and Central Jakarta",
    name: "PD PAL JAYA Provincial Government of DKI Jakarta",
    address: "Jl. Sultan Agung No.1",
    numberDate: "528/-1.712.8 29/04/2019",
    value: "292.248.000",
    contract: "27/07/2019",
    handover: "27/07/2019",
  },
  {
    no: "5",
    field: "Technical Advice on Strengthening the Ciliman River Bank",
    subField: "Water Civil Engineering Engineering",
    location: "Banten Province",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Syech Nawawi Al-Batani, Curug- Palima",
    numberDate: "900/SP.18.2.9/PJSA- DPUPR/IV/2019 30/04/2019",
    value: "88.694.000",
    contract: "30/07/2019",
    handover: "30/07/2019",
  },
  {
    no: "6",
    field:
      "Equipment and Machinery Capital Expenditures - Procurement of Other Office Equipment",
    subField: "Other Service",
    location: "Karang Asem Regency",
    name: "Department of Youth and Sports Education",
    address: "Jl. Veteran (Jalur 11) - Amlapura",
    numberDate: "027/17/SET/VI/Disdi kpora/2019 11/6/2019",
    value: "195.992.500",
    contract: "9/9/2019",
    handover: "9/9/2019",
  },
  {
    no: "7",
    field:
      "Expenditures for New Classroom Development Planning Consultants (RKB) Services at SMKN 1 PADAHERANG",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Veteran (Jalur 11) - AmlapuraJl. Dr. Radjiman No. 6 Bandung",
    numberDate: "117/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.246.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "8",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) at SMKN1 Cijulang",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "118/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.235.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "9",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) for SMKN 1 Kadipaten",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Tasikmalaya",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "116/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.224.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "10",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Study Services, Research and Technical Assistance",
    location: "Subang",
    name: "Department of Youth and Sports Tourism Subang",
    address: "Jl. A. Yani No.57 Pasirkareumbi",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "11",
    field:
      "Expenditures for Consultancy Services for Infrastructure Development Planning in Bogor (Package I)",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bogor",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/217- SPK/Konsul.Perenc/I nfrastruktur- Pkt.1/SMK/IV/2019 24/04/2019",
    value: "32.565.000",
    contract: "27/5/2019",
    handover: "28/5/2019",
  },
  {
    no: "12",
    field:
      "Expenditures for USB Development Planning Consultants at SMKN 1 Bungursari Purwakarta",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Purwakarta",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "13",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Ciamis",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "14",
    field:
      "Creation of GNSS/Flat Sipat Software",
    subField: "Telematics",
    location: "Geospatial Information Agency (BIG)",
    name: "Geospatial Information Agency (BIG)",
    address: "Jl. Raya Jakarta- Bogor KM. 46 Cibinong, Kab. Bogor",
    numberDate: "28.01/SPK/PPK- PJKGG/08/2019 28/08/2019",
    value: "80.080.000",
    contract: "26/9/2019",
    handover: "26/9/2019",
  },
  {
    no: "15",
    field:
      "Procurement of Maintenance of 3D Screening System Security Facilities for Fiscal Year 2019",
    subField: "Telematics",
    location: "Gowa, South Sulawesi",
    name: "Ministry of Law and Human Rights South Sulawesi Regional Office",
    address: "Jl. Lembaga Bolangi Desa Timbusseng Kec. Pattallassang Kab. Gowa",
    numberDate: "W23.PAS2.UM.03.0 5-333 28/09/2019",
    value: "98.527.800",
    contract: "02/10/2019",
    handover: "02/10/2019",
  },
  {
    no: "16",
    field:
      "Work Planning Consultancy Services Preparation of GIS Based Road and Bridge Infrastructure Database Sumedang.",
    subField: "Telematics/ Transportation Civil Engineering",
    location: "Sumedang District",
    name: "District Regional Research and Development Planning Agency",
    address: "Jl. Prabu Gajah Agung No. 09 Sumedang",
    numberDate: "02/SP/PPK- GIS/BAPPPPEDA/20 19 01/07/2019",
    value: "171.292.000",
    contract: "28/09/2019",
    handover: "28/09/2019",
  },
  {
    no: "17",
    field:
      "Review of Haurwangi Rest Area Development (Continued)",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Cianjur District",
    name: "District Public Works & Spatial Planning Department.",
    address: "Jl. Adi Sucipto No. 2 Cianjur",
    numberDate: "32/600- BG.PUPR/SPK-Rest Area Haurwangi/II/2016 25/02/2019",
    value: "67.507.000",
    contract: "25/04/2019",
    handover: "25/04/2019",
  },
  {
    no: "18",
    field:
      "Shopping for Goods/Services Consultancy Study of the Potential of Community Cultural Spaces for the Revitalization of People's Markets in West Java Towards Champion Markets",
    subField: "Study, Research and Technical Assistance Services",
    location: "West Java Province",
    name: "West Java Province Department of Industry and Trade",
    address: "Jl. Asia Afrika No. 146 Bandung",
    numberDate: "027/BJ-3853/PDN 25/06/2019",
    value: "96.920.000",
    contract: "25/07/2019",
    handover: "25/07/2019",
  },
  {
    no: "19",
    field:
      "PR Planning Consultancy Services 11",
    subField: "Regional Planning / Spatial Planning",
    location: "Sumedang District",
    name: "Department of Public Works and Spatial Planning Bid. Highways District.",
    address: "Jl. RA Kartini No. 13 Sumedang",
    numberDate: "02/SP/15.001/APBD /PPK-PR 11/DPUPR/2019 16/04/2019",
    value: "78.782.000",
    contract: "14/06/2019",
    handover: "13/06/2019",
  },
  {
    no: "20",
    field:
      "PR Planning Consultancy Services 01",
    subField: "Regional Planning / Spatial Planning",
    location: "Sumedang District",
    name: "Department of Public Works and Spatial Planning Bid. Highways District.",
    address: "Jl. RA Kartini No. 13 Sumedang",
    numberDate: "03/SPK/15.020/BAN PROV/PPK-PR 01/DPUPR/2019 08/05/2019",
    value: "76.664.500",
    contract: "06/07/2019",
    handover: "04/07/2019",
  },
  {
    no: "21",
    field:
      "Creation of a Water Resources Information System (SDA)",
    subField: "Telematics",
    location: "West Java Provincial Government",
    name: "West Java Provincial Water Resources Service",
    address: "Jl. Braga No. 137 Bandung",
    numberDate: "600/SPK.2195.Sekre /2019 11/10/2019",
    value: "49.417.500",
    contract: "09/12/2019",
    handover: "09/12/2019",
  },
];

export default project2019;
