const project2021 = [
    {
      no: "1",
      field:
        "MRLL study on the Borobudur KSPN",
      subField: "Transportation",
      location: "Jakarta",
      name: "Ministry of Transportation Directorate General of Land Transportation",
      address: "Gedung Karya Jl. Merdeka Barat No.8 Jakarta",
      numberDate: "PL.107/215/2/SPK /SATKER- LLJ/VIII/2021 09/08/2021",
      value: "98.862.500",
      contract: "07/09/2021",
      handover: "07/09/2021",
    },
    {
      no: "2",
      field: "Preparation of Road and Bridge Priority Scale for the Gedebage Area",
      subField: "Road Civil",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34",
      numberDate: "027/01.0002/PL.0 6- Prc.SP.JJ./SPK/PPK M/DPU/2021 06/05/2021",
      value: "37.049.100",
      contract: "04/06/2021",
      handover: "04/06/2021",
    },
    {
      no: "3",
      field:
        "Consultancy Services for Study Room Rehabilitation at SMKN 1 Banjar, Banjar City",
      subField: "Architectural",
      location: "Banjar City",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3228/30.PRC.- REHAB.PSMK/DISD IK.KBR/2021 01/04/2021",
      value: "44.220.000",
      contract: "30/04/2021",
      handover: "30/04/2021",
    },
    {
      no: "4",
      field:
        "Study Room Rehabilitation Planning Consultancy Services SMKN 5 Kuningan Kab. Brass",
      subField: "Architecture",
      location: "Kuningan Regency",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3223/30.PRC.- REHAB.PSMK/DISD IK.JBR/2021 01/04/2021",
      value: "44.220.000",
      contract: "30/04/2021",
      handover: "30/04/2021",
    },
    {
      no: "5",
      field: "Creation of the INSW Integrated Control System",
      subField: "Telematics",
      location: "DKI Jakarta",
      name: "Ministry of Communication and Informatics",
      address: "Jl. Medan Merdeka Barat No.17, Jakarta",
      numberDate: "1630/PPK/KOMIN FO/DJ- SDPPI.4/08/2021 13/08/2021",
      value: "197.900.000",
      contract: "10/11/2021",
      handover: "10/11/2021",
    },
    {
      no: "6",
      field:
        "Review of Tegalwaru District Office Development Planning",
      subField: "Architecture",
      location: "Purwakarta Regency",
      name: "Office of Spatial Planning and Settlement of Purwakarta Regency",
      address: "Jl. KK Singawinata No. 116",
      numberDate: "601/12.SPK/Peren c.Pemb- Kec.Tegalwaru/Ta bang/V/2021 09/04/2021",
      value: "56.300.000",
      contract: "08/05/2021",
      handover: "08/05/2021",
    },
    {
      no: "7",
      field:
        "Population Data Synchronization With Other Ministries/Agencies",
      subField: "Telematics",
      location: "DKI Jakarta",
      name: "Ministry of Home Affairs of the Republic of Indonesia",
      address: "Jl. Raya Pasar Minggu Km.19 Jakarta Selatan",
      numberDate: "027/4844/PIAK.20 21 10/09/2021",
      value: "561.373.493",
      contract: "10/12/2021",
      handover: "10/12/2021",
    },
    {
      no: "8",
      field:
        "Engineering Planning for Sidewalk Development IV",
      subField: "Road Civil",
      location: "Bandung City",
      name: "Bandung City Government Public Works Service",
      address: "Jl. Cianjur No.34",
      numberDate: "027/01.0002/PL.0 4- Prc.Pemb.Trot/SPK /PPKM/DPU/2021 14/09/2021",
      value: "45.595.000",
      contract: "13/10/2021",
      handover: "13/10/2021",
    },
    {
      no: "9",
      field:
        "Work on the Preparation of Technical Guidelines to Support the Food Security Program in the Lamunti Dadahup Area",
      subField: "Management",
      location: "Lamunti Dadahup area",
      name: "Directorate of Planning for the Realization of Transmigration Areas, Ministry of Villages",
      address: "Jln. TMP. Kalibata No. 17 Jakarta Selatan 12750",
      numberDate: "SPK.16/PPK-P2KT- PPKT/IX/2021 06/09/2021",
      value: "479.853.000",
      contract: "06/12/2021",
      handover: "06/12/2021",
    },
    {
      no: "10",
      field:
        "1 Provincial Management Consultant Jobs-4",
      subField: "Management",
      location: "West Java",
      name: "Department of Housing and Settlements Regional Government of West Java Province",
      address: "Jl. Kawaluyaan II No.4",
      numberDate: "03/SP/KMP4/2021 18/06/2021",
      value: "556.179.580",
      contract: "20/12/2021",
      handover: "20/12/2021",
    },
    {
      no: "11",
      field:
        "Compilation of the Study on the Development of the Padalarang Station TOD and the Impact of the Existence of the High Speed Train Station",
      subField: "Research Studies and Technical Assistance",
      location: "Padalarang",
      name: "Regional Research and Development Development Planning Agency ",
      address: "Perkantoran Pemkab Jl. Raya Padalarang-Cisarua Km.2 Ngamprah",
      numberDate: "027/1754/SPK/Ba ppelitbangda/202 1 15/11/2021",
      value: "97.372.000",
      contract: "14/12/2021",
      handover: "14/12/2021",
    },
    {
      no: "12",
      field:
        "Expenditures for USB Development Planning Consultants at SMKN 1 Bungursari Purwakarta",
      subField: "Research Studies and Technical Assistance",
      location: "Padalarang",
      name: "Regional Research and Development Development Planning Agency ",
      address: "Perkantoran Pemkab Jl. Raya Padalarang-Cisarua Km.2 Ngamprah",
      numberDate: "027/1787/SPK/Ba ppelitbangda/202 1 17/11/2021",
      value: "97.163.000",
      contract: "16/12/2021",
      handover: "16/12/2021",
    },
    {
      no: "13",
      field:
        "Research and Development Studies in the Health Sector (Epidemiological Surveillance in Purwakarta Regency)",
      subField: "Management",
      location: "Purwakarta Regency",
      name: "Regional Research and Development Planning Agency",
      address: "Jl. Gandanegara No.25",
      numberDate: "007/SPK-Kajian Kesehatan/XI/202 1 22/11/2021",
      value: "49.307.500",
      contract: "22/12/2021",
      handover: "16/12/2021",
    },
    {
      no: "14",
      field:
        "Review of Discipline Enforcement Technical Guidelines",
      subField: "Management",
      location: "Bogor City",
      name: "Bogor City Government BKPSDM Bogor City",
      address: "Jl. Julang 1 No.7 Bogor",
      numberDate: "027/09/DIS/MDK. D/SPK/IV/2021 20/04/2021",
      value: "57.200.000",
      contract: "18/06/2021",
      handover: "17/06/2021",
    },
    {
      no: "15",
      field:
        "Procurement of Planning Consultancy Services in the framework of Preparation of Landslide Disaster Management Plans",
      subField: "Management",
      location: "Sumedang Regency",
      name: "District Government Sumedang Regional Disaster Management Agency",
      address: "Jl. Empang No. 01",
      numberDate: "02.002/PPK/SP- RPBLONGSOR/BPB D/2021 26/02/2021",
      value: "94.323.515",
      contract: "27/03/2021",
      handover: "27/03/2021",
    },
    {
      no: "16",
      field:
        "Making Situation Map of Forest Area Boundary in Wlingi",
      subField: "Other Services/ Mapping",
      location: "East Java",
      name: "Ministry of Agrarian Affairs and Spatial Planning/National Land Agency Directorate General of Land and Spatial Surveys and Mapping",
      address: "Jl. Kuningan Barat I Nomor 1 Jakarta Selatan",
      numberDate: "172.4/SPMK/PPK- 5543/VI/2021 21/06/2021",
      value: "1.939.999.996",
      contract: "12/09/2021",
      handover: "03/09/2021",
    },
    {
      no: "17",
      field:
        "Making Situation Map of Forest Area Boundary in Yeh Leh Yeh Lebah and Budeng",
      subField: "Mapping",
      location: "Bali",
      name: "Ministry of Agrarian Affairs and Spatial Planning/National Land Agency",
      address: "Jl. Kuningan Barat 1 Nomor 1 Jakarta Selatan",
      numberDate: "139.4/KONTRAK/P PK-5543/V/2021 19/05/2021",
      value: "929.374.600",
      contract: "24/07/2021",
      handover: "11/08/2021",
    },
    {
      no: "18",
      field:
        "Inventory of Peat Ecosystem Characteristics in 4 Peat Hydrological Units (KHG) in West Kalimantan Province (Package V)",
      subField: "Other Services",
      location: "West Kalimantan",
      name: "Ministry of Environment and Forestry Directorate General of Pollution Control and Environmental Damage",
      address: "Jl. D.I. Panjaitan Kav.24 Kebon Nanas, Jakarta",
      numberDate: "SP-596/PPK-PKG/SMPEI- IFAD/07/2021 19/07/2021",
      value: "1.300.598.500",
      contract: "23/09/2021",
      handover: "05/10/2021",
    },
    {
      no: "19",
      field:
        "Tin Dome Mosque Design Conception Consultant",
      subField: "Architecture/Civil Building",
      location: "Pangkal Pinang City",
      name: "Department of Public Works and Spatial Planning",
      address: "Jl. Rasakunda Girimaya Pangkalpinang",
      numberDate: "15/SPK-KONSLT PMKT CK/APBDP/XI/202 102/11/2021",
      value: "94.890.000",
      contract: "30/12/2021",
      handover: "30/12/2021",
    },
    {
      no: "20",
      field:
        "Business Activity Data Updating Consultancy Services in Bogor City",
      subField: "Informatics Management",
      location: "Bogor City",
      name: "Bogor City Government Environment Service",
      address: "Jl. Paledang No.43 Kota Bogor",
      numberDate: "006/Kontrak/Kons. Upd.Data/TL/DLH/ III/2021 08/03/2021",
      value: "99.385.000",
      contract: "05/06/2021",
      handover: "03/06/2021",
    },
    {
      no: "21",
      field:
        "Jasa Konsultansi Perencanaan Pembangunan Ruang Praktek Sekolah (RPS) SMK PGRI Kab. Subang",
      subField: "Architecture",
      location: "Regency Subang",
      name: "West Java Provincial Education Office",
      address: "Jl. Dr. Radjiman No.6 Bandung",
      numberDate: "3164/30.PRC.- RPS.PSMK/DISDIK. JBR/2021 02/02/2021",
      value: "44.154.000",
      contract: "03/03/2021",
      handover: "03/03/2021",
    },
  ];
  
  export default project2021;
  