const project2019 = [
  {
    no: "1",
    field:
      "Preparation of Regional Action Plans (RAD) Activities of Disaster Management Plans (RPB)",
    subField: "Study Services, Research and Technical Assistance",
    location: "Sumedang District",
    name: "Regional Disaster Management Agency (BPBD)",
    address: "Jl. Empang No. 01 Sumedang 45312",
    numberDate: "02.1/SPK/RAD/BPBD /2019 5/3/2019",
    value: "90.948.000",
    contract: "3/4/2019",
    handover: "3/4/2019",
  },
  {
    no: "2",
    field: "Pedestrian Bridge Planning Consultant Services",
    subField: "Transportation Civil Engineering Engineering",
    location: "Bandung City",
    name: "Bandung City Department of Transportation",
    address: "Jl. Soekarno Hatta No.205",
    numberDate: "03/PPK-PPSTK- PPJPO/II/DISHUB/20 19 12/2/2019",
    value: "98.395.000",
    contract: "12/4/2019",
    handover: "12/4/2019",
  },
  {
    no: "3",
    field:
      "Consultancy Services for Heavy Rehabilitation Planning of SDN Tanjung Priok Building 02/03",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "DKI Jakarta",
    name: "Region I Education Office North Jakarta Administrative City",
    address: "Jl. Laksda Yos Sudarso No.27-29",
    numberDate: "463/1.851.2.061 12/2/2019",
    value: "76.700.000",
    contract: "13/03/2019",
    handover: "13/03/2019",
  },
  {
    no: "4",
    field:
      "Preparation of DED for the Development of the Senopati & Bendungan Hilir Waste Water Pipeline Network",
    subField: "Water Civil Engineering Engineering",
    location: "South Jakarta and Central Jakarta",
    name: "PD PAL JAYA Provincial Government of DKI Jakarta",
    address: "Jl. Sultan Agung No.1",
    numberDate: "528/-1.712.8 29/04/2019",
    value: "292.248.000",
    contract: "27/07/2019",
    handover: "27/07/2019",
  },
  {
    no: "5",
    field: "Technical Advice on Strengthening the Ciliman River Bank",
    subField: "Water Civil Engineering Engineering",
    location: "Banten Province",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Syech Nawawi Al-Batani, Curug- Palima",
    numberDate: "900/SP.18.2.9/PJSA- DPUPR/IV/2019 30/04/2019",
    value: "88.694.000",
    contract: "30/07/2019",
    handover: "30/07/2019",
  },
  {
    no: "6",
    field:
      "Equipment and Machinery Capital Expenditures - Procurement of Other Office Equipment",
    subField: "Other Service",
    location: "Karang Asem Regency",
    name: "Department of Youth and Sports Education",
    address: "Jl. Veteran (Jalur 11) - Amlapura",
    numberDate: "027/17/SET/VI/Disdi kpora/2019 11/6/2019",
    value: "195.992.500",
    contract: "9/9/2019",
    handover: "9/9/2019",
  },
  {
    no: "7",
    field:
      "Expenditures for New Classroom Development Planning Consultants (RKB) Services at SMKN 1 PADAHERANG",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Veteran (Jalur 11) - AmlapuraJl. Dr. Radjiman No. 6 Bandung",
    numberDate: "117/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.246.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "8",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) at SMKN1 Cijulang",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Pangandaran",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "118/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.235.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "9",
    field:
      "Expenditures for Planning Consultants for the Development of New Classrooms (RKB) for SMKN 1 Kadipaten",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Tasikmalaya",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "116/037/PRC/RKB- Rehab/SMKN.JBR/2 019 12/3/2019",
    value: "16.224.000",
    contract: "11/4/2019",
    handover: "11/4/2019",
  },
  {
    no: "10",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Study Services, Research and Technical Assistance",
    location: "Subang",
    name: "Department of Youth and Sports Tourism Subang",
    address: "Jl. A. Yani No.57 Pasirkareumbi",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "11",
    field:
      "Expenditures for Consultancy Services for Infrastructure Development Planning in Bogor (Package I)",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bogor",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/217- SPK/Konsul.Perenc/I nfrastruktur- Pkt.1/SMK/IV/2019 24/04/2019",
    value: "32.565.000",
    contract: "27/5/2019",
    handover: "28/5/2019",
  },
  {
    no: "12",
    field:
      "Expenditures for USB Development Planning Consultants at SMKN 1 Bungursari Purwakarta",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Purwakarta",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "13",
    field:
      "Shopping Design Planning For Contractual Activities",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Ciamis",
    name: "Education Authorities West Java",
    address: "Jl. Dr. Radjiman No. 6 Bandung",
    numberDate: "027/040/SPK/PPK/D isparpora/IV/2019 8/4/2019",
    value: "74.074.000",
    contract: "22/5/2019",
    handover: "22/5/2019",
  },
  {
    no: "14",
    field:
      "Creation of GNSS/Flat Sipat Software",
    subField: "Telematics",
    location: "Geospatial Information Agency (BIG)",
    name: "Geospatial Information Agency (BIG)",
    address: "Jl. Raya Jakarta- Bogor KM. 46 Cibinong, Kab. Bogor",
    numberDate: "28.01/SPK/PPK- PJKGG/08/2019 28/08/2019",
    value: "80.080.000",
    contract: "26/9/2019",
    handover: "26/9/2019",
  },
  {
    no: "15",
    field:
      "Procurement of Maintenance of 3D Screening System Security Facilities for Fiscal Year 2019",
    subField: "Telematics",
    location: "Gowa, South Sulawesi",
    name: "Ministry of Law and Human Rights South Sulawesi Regional Office",
    address: "Jl. Lembaga Bolangi Desa Timbusseng Kec. Pattallassang Kab. Gowa",
    numberDate: "W23.PAS2.UM.03.0 5-333 28/09/2019",
    value: "98.527.800",
    contract: "02/10/2019",
    handover: "02/10/2019",
  },
  {
    no: "16",
    field:
      "Work Planning Consultancy Services Preparation of GIS Based Road and Bridge Infrastructure Database Sumedang.",
    subField: "Telematics/ Transportation Civil Engineering",
    location: "Sumedang District",
    name: "District Regional Research and Development Planning Agency",
    address: "Jl. Prabu Gajah Agung No. 09 Sumedang",
    numberDate: "02/SP/PPK- GIS/BAPPPPEDA/20 19 01/07/2019",
    value: "171.292.000",
    contract: "28/09/2019",
    handover: "28/09/2019",
  },
  {
    no: "17",
    field:
      "Review of Haurwangi Rest Area Development (Continued)",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Cianjur District",
    name: "District Public Works & Spatial Planning Department.",
    address: "Jl. Adi Sucipto No. 2 Cianjur",
    numberDate: "32/600- BG.PUPR/SPK-Rest Area Haurwangi/II/2016 25/02/2019",
    value: "67.507.000",
    contract: "25/04/2019",
    handover: "25/04/2019",
  },
  {
    no: "18",
    field:
      "Shopping for Goods/Services Consultancy Study of the Potential of Community Cultural Spaces for the Revitalization of People's Markets in West Java Towards Champion Markets",
    subField: "Study, Research and Technical Assistance Services",
    location: "West Java Province",
    name: "West Java Province Department of Industry and Trade",
    address: "Jl. Asia Afrika No. 146 Bandung",
    numberDate: "027/BJ-3853/PDN 25/06/2019",
    value: "96.920.000",
    contract: "25/07/2019",
    handover: "25/07/2019",
  },
  {
    no: "19",
    field:
      "PR Planning Consultancy Services 11",
    subField: "Regional Planning / Spatial Planning",
    location: "Sumedang District",
    name: "Department of Public Works and Spatial Planning Bid. Highways District.",
    address: "Jl. RA Kartini No. 13 Sumedang",
    numberDate: "02/SP/15.001/APBD /PPK-PR 11/DPUPR/2019 16/04/2019",
    value: "78.782.000",
    contract: "14/06/2019",
    handover: "13/06/2019",
  },
  {
    no: "20",
    field:
      "PR Planning Consultancy Services 01",
    subField: "Regional Planning / Spatial Planning",
    location: "Sumedang District",
    name: "Department of Public Works and Spatial Planning Bid. Highways District.",
    address: "Jl. RA Kartini No. 13 Sumedang",
    numberDate: "03/SPK/15.020/BAN PROV/PPK-PR 01/DPUPR/2019 08/05/2019",
    value: "76.664.500",
    contract: "06/07/2019",
    handover: "04/07/2019",
  },
  {
    no: "21",
    field:
      "Creation of a Water Resources Information System (SDA)",
    subField: "Telematics",
    location: "West Java Provincial Government",
    name: "West Java Provincial Water Resources Service",
    address: "Jl. Braga No. 137 Bandung",
    numberDate: "600/SPK.2195.Sekre /2019 11/10/2019",
    value: "49.417.500",
    contract: "09/12/2019",
    handover: "09/12/2019",
  },
  {
    no: "22",
    field:
      "Preparation of Ciliwung DAS IPAL DED",
    subField: "Water Civil Engineering",
    location: "Ministry of Environment and Forestry",
    name: "Directorate of Water Pollution Control, Ministry of Environment and Forestry",
    address: "Jl. D.I. Panjaitan, Kebon Nanas Jakarta",
    numberDate: "142/PPA.01/PPK/20 19 02/09/2019",
    value: "97.250.000",
    contract: "31/10/2019",
    handover: "31/10/2019",
  },
  {
    no: "23",
    field:
      "Shop for Pavement and Road Drainage Engineering Planning Consultancy Services I",
    subField: "Transportation Civil Engineering",
    location: "Bandung City",
    name: "Bandung City Government Planning Sector",
    address: "Jl. Cianjur No. 34 Bandung",
    numberDate: "027/43.04/PL.01/SP K/PPKm/DPU/2019 17/09/2019",
    value: "48.909.300",
    contract: "16/10/2019",
    handover: "16/10/2019",
  },
  {
    no: "24",
    field:
      "Development of the SPBE Application Package-3 (Web Service for the Ministry of Home Affairs Administration and Consultation Services Application)",
    subField: "Telematics",
    location: "Ministry of Home Affairs of the Republic of Indonesia",
    name: "Secretariat General of the Ministry of Home Affairs of the Republic of Indonesia",
    address: "Jl. Medan Merdeka Utara No. 7, Jakarta Pusat",
    numberDate: "027/4392/Pusdatin 23/09/2019",
    value: "98.296.000",
    contract: "21/11/2019",
    handover: "21/11/2019",
  },
  {
    no: "25",
    field:
      "Planning (DED) for Waste Water Management in the PT Factory Environment. Coats Rejo Indonesia",
    subField: "Water / Environmental Civil Engineering",
    location: "PT. Coats Rejo Indonesia, Bogor",
    name: "PT. Coats Rejo Indonesia",
    address: "Jl. Tajur No. 24 Bogor",
    numberDate: "005/PUR/CRI/DED- ENG/2019 06/02/2019",
    value: "700.450.000",
    contract: "07/05/2019",
    handover: "07/05/2019",
  },
  {
    no: "26",
    field:
      "SME Product Design and Packaging for Fiscal Year 2019",
    subField: "Study, Research and Technical Assistance Services",
    location: "Purwakarta Regency",
    name: "Department of Cooperatives, Small and Medium Enterprises, Trade & Industry",
    address: "Jl. Jend. Ahmad Yani No. 170 Purwakarta",
    numberDate: "012/SPK/PDKPI/XII/ 2019 02/12/2019",
    value: "70.000.000",
    contract: "10/12/2019",
    handover: "10/12/2019",
  },
  {
    no: "27",
    field:
      "Master Plan for Improving the Quality of Slum Settlements",
    subField: "Regional Planning / Spatial Planning",
    location: "Belitung Regency",
    name: "District Public Works and Public Housing Department. Belitung",
    address: "Jl. Membalong KM. 7 Perawas Tanjungpandan, Kab. Belitung",
    numberDate: "02/PRCN/KONS- RENDUK PKPK/DPUPR.V/APB D/2019 16/10/2019",
    value: "261.415.000",
    contract: "15/12/2019",
    handover: "18/12/2019",
  },
  {
    no: "28",
    field:
      "Ecopark DED Planning",
    subField: "Building and Landscape Environmental Design",
    location: "Belitung Regency",
    name: "District Public Works and Public Housing Department. Belitung",
    address: "Jl. Membalong KM. 7 Perawas Tanjungpandan, Kab. Belitung",
    numberDate: "01/SPK/DED- Ecopark/APBD- P/DPUPR/2019 11/10/2019",
    value: "99.500.000",
    contract: "10/11/2019",
    handover: "18/11/2019",
  },
  {
    no: "29",
    field:
      "SIPP Application Development",
    subField: "Telematics",
    location: "Bandung City",
    name: "Bandung City Regional Revenue Management Agency",
    address: "Jl. Wastukancana No. 2 Bandung",
    numberDate: "027/16/21.001/21.0 4-PPK/2019 20/06/2019",
    value: "94.578.000",
    contract: "17/09/2019",
    handover: "17/09/2019",
  },
  {
    no: "30",
    field:
      "Consultant Services for Planning the Building Improvement of the West Java Province Mental Hospital Guard Post",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "West Java Province",
    name: "Provincial Health Service. West Java",
    address: "Jl. Kol. Masturi KM. 7 Cisarua Kab. Bandung Barat",
    numberDate: "027/4061/RSJ 28/02/2019",
    value: "6.400.000",
    contract: "29/4/2019",
    handover: "29/4/2019",
  },
  {
    no: "31",
    field:
      "Review of SOPs for the Implementation of UKPBJ Goods and Services Kab. Purwakarta",
    subField: "Study, Research and Technical Assistance Services",
    location: "Purwakarta Regency",
    name: "District Regional Secretariat. Purwakarta",
    address: "Jl. Gandanegara No. 25 Purwakarta",
    numberDate: "21.21/02/SPK/BLPBJ /SOP/X/2019 31/10/2019",
    value: "27.280.000",
    contract: "29/11/2019",
    handover: "29/11/2019",
  },
  {
    no: "32",
    field:
      "Technical Planning for Development, Management and Conservation Programs for Rivers, Lakes and Other Water Resources TA APBD. 2020",
    subField: "Water / Environmental Civil Engineering",
    location: "Bekasi District",
    name: "Bekasi Regency Public Works and Spatial Planning Department",
    address: "Komplek Pemerintahan Kab. Bekasi Desa Sukamahi Kec. Cikarang Pusat Kab. Bekasi",
    numberDate: "602.3/30.3/KONS- PERTEK/SPP- PPK/PSDA- DPUPR/2019 28/10/2019",
    value: "273.500.000",
    contract: "26/12/2019",
    handover: "26/12/2019",
  },
  {
    no: "33",
    field:
      "Assistance in Arranging Slum Area Facilities and Infrastructure Package 12",
    subField: "Regional Planning / Spatial Planning",
    location: "Bandung District",
    name: "Department of Housing and Residential Areas and Land",
    address: "Jl. Taya Soreang KM 17, Soreang Kab. Bandung",
    numberDate: "663/1131/SPK/PEN DAMPINGAN PSPKK PAKET 12/KWS/VI/2019 14/06/2019",
    value: "98.560.000",
    contract: "10/11/2019",
    handover: "10/11/2019",
  },
  {
    no: "34",
    field:
      "WEB-Based Identification of BTS Towers in Bandung Regency",
    subField: "Telematics",
    location: "Bandung District",
    name: "District Public Works and Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang- Banjaran KM 3, Soreang Bandung",
    numberDate: "650/02/KTRK/MENA RA BTS. WEB- PUTR/TR/IX/2019 04/09/2019",
    value: "176.935.000",
    contract: "02/12/2019",
    handover: "02/12/2019",
  },
  {
    no: "35",
    field:
      "Preparation of Network Development Environment Documents SPAM Rural District. Dandang",
    subField: "Environment",
    location: "East Belitung Regency",
    name: "District Public Works and Spatial Planning Department. East Belitung",
    address: "Komplek Perkantoran Pemkab Beltim Jl. Raya Manggar- Gantung – Kab. Belitung Timur",
    numberDate: "02/SPK/PPK/DISPUT R-UKL-UPL SPAM DENDANG/2019 04/11/2019",
    value: "74.800.000",
    contract: "18/12/2019",
    handover: "18/12/2019",
  },
  {
    no: "36",
    field:
      "Procurement of Research Consultancy Services for Development Design of Livestock Commodity Clusters in West Java",
    subField: "Study, Research and Technical Assistance Services",
    location: "West Java Province",
    name: "Provincial Food & Livestock Security Service. West Java",
    address: "Jl. Kawaluyaan Indah Raya No. 6 Gedung BPKAD LT. 5 Soekarno Hatta - Bandung",
    numberDate: "24/SP/K.Klaster/Pro d/APBD/IX/2019 24/09/2019",
    value: "241.890.000",
    contract: "22/12/2019",
    handover: "17/12/2019",
  },
  {
    no: "37",
    field:
      "Preparation of Albert Wheel Loader and Bulldozer Age Data",
    subField: "Study, Research and Technical Assistance Services",
    location: "Bandung District",
    name: "District Public Works & Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang- Banjaran KM. 3 Soreang",
    numberDate: "602/PBAL.JK.23.10.0 7/SPK/DPUTR/VIII/2 019 12/08/2019",
    value: "79.750.000",
    contract: "09/11/2019",
    handover: "08/11/2019",
  },
  {
    no: "38",
    field:
      "TPT Region 7 Development Planning",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bandung District",
    name: "District Public Works & Spatial Planning Department. Bandung",
    address: "Jl. Raya Soreang- Banjaran KM. 3 Soreang",
    numberDate: "602.1/7/KTR/P.17.0 1.jkp.07/DPUTR/201 9 12/04/2019",
    value: "99.638.000",
    contract: "28/06/2019",
    handover: "28/06/2019",
  },
  {
    no: "39",
    field:
      "Preparation of Community Satisfaction Index Survey",
    subField: "Study, Research and Technical Assistance Services",
    location: "Bekasi District",
    name: "Department of Communication, Informatics, Coding and Statistics District. Bekasi",
    address: "Komp. Perkantoran Pemerintahan Kab. Bekasi",
    numberDate: "027/9474/PBJ.Disko minfo.1/2019 01/11/2019",
    value: "90.530.000",
    contract: "13/12/2019",
    handover: "13/12/2019",
  },
  {
    no: "40",
    field:
      "Preparation of Development Guidance Documents for the Railway Traffic and Transportation Sector for 2020-2024",
    subField: "Study, Research and Technical Assistance Services",
    location: "Ministry of Transportation",
    name: "Ministry Transportation Directorate General of Railways",
    address: "Graha Jatibaru Blok C-7, Jl. Jatibaru Timur No. 56A Cideng Jakarta",
    numberDate: "03/JL- BIM/LLA.KA/VII/201 9 11/07/2019",
    value: "96.636.100",
    contract: "09/10/2019",
    handover: "09/10/2019",
  },
  {
    no: "41",
    field:
      "Technical Guidance on Procedures for Determining Railway Service Crossings",
    subField: "Study, Research and Technical Assistance Services",
    location: "Ministry of Transportation",
    name: "Ministry Transportation Directorate General of Railways",
    address: "Graha Jatibaru Blok C-7, Jl. Jatibaru Timur No. 56A Cideng Jakarta",
    numberDate: "03/JL- BIM/LLA.KA/VII/201 9 11/07/ 2019",
    value: "105.281.000",
    contract: "10/8/2019",
    handover: "10/8/2019",
  },
  {
    no: "42",
    field:
      "Preparation of UKL/UPL Documents for Multipurpose Buildings, District. Payangan",
    subField: "Environment",
    location: "Gianyar District",
    name: "District Public Works and Spatial Planning Department. Gianyar, Bali",
    address: "Jl. Raya Bona No. , Gianyar, Bali",
    numberDate: "640/9021/DPUPR/2 019 09/10/2019",
    value: "74.387.500",
    contract: "08/12/2019",
    handover: "03/12/2019",
  },
  {
    no: "43",
    field:
      "Preparation of Clean Water Building Inventory Documents",
    subField: "Study, Research and Technical Assistance Services/ Environment",
    location: "Indramayu District",
    name: "Department of Housing, Settlement Areas and Land District. Indramayu",
    address: "Jl. Wiralodra No. 35/A Indramayu",
    numberDate: "690/VIII.19.752.a.IN TV.BANG.AB.II/PPK. BPPL 30/08/2019",
    value: "83.985.000",
    contract: "28/10/2019",
    handover: "28/10/2019",
  },
  {
    no: "44",
    field:
      "Preparation of Clean Water Building Inventory Document Wil. Kandanghaur (Continued)",
    subField: "Study, Research and Technical Assistance Services/ Environment",
    location: "Indramayu District",
    name: "Department of Housing, Settlement Areas and Land District. Indramayu",
    address: "Jl. Wiralodra No. 35/A Indramayu",
    numberDate: "690/XI.19.1059.INT V.BANG.AB.II/PPK.B PPL 18/11/2019",
    value: "28.366.000",
    contract: "09/12/2019",
    handover: "09/12/2019",
  },
  {
    no: "45",
    field:
      "East Belitung Regency IKPLHD Preparation Consultancy Services",
    subField: "Environment",
    location: "East Belitung District",
    name: "District Environmental Service. East Belitung",
    address: "Jl. Raya Manggar- Gantung Dusun Manggarawan Manggar",
    numberDate: "01/SPK/KONS- IKPLHD/DLH/2019 27/09/2019",
    value: "29.782.500",
    contract: "25/11/2019",
    handover: "22/11/2019",
  },
  {
    no: "46",
    field:
      "Shopping for Planning Consultancy Services (Planning) for Motorcycle Parking Canopy Work, Toilet Maintenance and Repair, DW Building Spatial Arrangement, PWRI Spatial Arrangement for the DPRD Secretariat Building",
    subField: "Building and Landscape Environmental Design",
    location: "Provincial DPRD Secretariat. West Java",
    name: "Provincial DPRD Secretariat. West Java",
    address: "Jl. Dipenogoro No. 27 Bandung",
    numberDate: "027/2896/02/SETW AN/2019 09/10/2019",
    value: "51.195.000",
    contract: "29/10/2019",
    handover: "29/10/2019",
  },
  {
    no: "47",
    field:
      "Report on the Implementation of the Bogor City Program to Become a Halal City",
    subField: "Study, Research and Technical Assistance Services",
    location: "Bogor city",
    name: "Economic Administration Section, Bogor City",
    address: "Jl. Ir. H. Juanda No. 10 Bogor",
    numberDate: "027/04- Kota.Halal.Adekom. KS/KPA/XI/2019 04/11/2019",
    value: "39.600.000",
    contract: "03/12/2019",
    handover: "03/12/2019",
  },
  {
    no: "48",
    field:
      "DIKPLHD Preparation Consultancy Services",
    subField: "Environment",
    location: "Bogor city",
    name: "Environmental Service, Bogor City",
    address: "Jl. Paledang No. 43 Bogor",
    numberDate: "027/02/PPK/SPK/DI KPLHD/IX/2019 16/09/2019",
    value: "69.850.000",
    contract: "16/12/2019",
    handover: "16/12/2019",
  },
  {
    no: "49",
    field:
      "Trustee Consultancy Shopping",
    subField: "Study, Research and Technical Assistance Services",
    location: "Bogor city",
    name: "Bogor City Regional Disaster Management Agency",
    address: "Jl. Pool Binamarga No. 2, Bogor",
    numberDate: "027/02/Perwali/PPK /BPBD/2019 08/08/2019",
    value: "43.450.000",
    contract: "06/09/2019",
    handover: "06/09/2019",
  },
  {
    no: "50",
    field:
      "DED New Development of Pondoksalam District Office",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Purwakarta Regency",
    name: "District Spatial Planning and Settlement Department. Purwakarta",
    address: "Jl. KK Singawinata No. 116 Purwakarta",
    numberDate: "601/01- SPK/DED.PONDOKS ALAM/Tabang/X/20 19 17/10/2019",
    value: "89.925.000",
    contract: "16/12/2019",
    handover: "09/12/2019",
  },
  {
    no: "51",
    field:
      "Technical Planning for Rehabilitation of Buildings and Irrigation Channels in 2020",
    subField: "Water Civil Engineering",
    location: "Purwakarta Regency",
    name: "Department of Public Works, Highways and Irrigation District. Purwakarta",
    address: "Jl. Purnawarman Barat No. 6A Purwakarta",
    numberDate: "23/SPK.KS.SDA/PER TEK.ABT/PPK.KPA- DPUBMP/XI/2019 08/11/2019",
    value: "94.875.000",
    contract: "22/12/2019",
    handover: "20/12/2019",
  },
  {
    no: "52",
    field:
      "Consultancy Services for Preparing the 2020-2024 Strategic Plan in the Railway Sector at the Western Java Railway Engineering Center",
    subField: "Study, Research and Technical Assistance Services",
    location: "West Java",
    name: "Ministry of Transportation",
    address: "Jl. Raya Gedebage No. 68 Bandung",
    numberDate: "PL.107/1/6/JKPR/PP K-RN/BTP-JABAR/XI- 2019 14/11/2019",
    value: "76.654.000",
    contract: "13/12/2019",
    handover: "13/12/2019",
  },
  {
    no: "53",
    field:
      "Shop for Consultancy Services for the Study of the Construction of the Curug Goong DED and Dayeuh Kolot Village",
    subField: "Water Civil Engineering",
    location: "Subang Regency",
    name: "District Tourism, Youth and Sports Department. Subang",
    address: "Jl. A. Yani No. 57 Pasirkeumbi Subang",
    numberDate: "027//SPK/PPK/Dispa rpora/X/2019 30/10/2019",
    value: "78.133.000",
    contract: "13/12/2019",
    handover: "13/12/2019",
  },
  {
    no: "54",
    field:
      "Shopping for Planning Consultancy Services for Feasibility Study of Mini SPAM Jaletreng River, Setu District",
    subField: "Water Civil Engineering",
    location: "South Tangerang City",
    name: "South Tangerang City Building and Spatial Planning Department",
    address: "Intermark Indonesia Associate Tower Lt. 3. Jl. Lingkar Timur No. 9 Kota Tangerang Selatan",
    numberDate: "900/049/SPK-P- KON/AM- SANITASI/DBPR/APB DP/2019 25/11/2019",
    value: "75.735.000",
    contract: "24/12/2019",
    handover: "20/12/2019",
  },
  {
    no: "55",
    field:
      "Natural Resources Technical Planning Package 2",
    subField: "Water Civil Engineering",
    location: "Bogor City",
    name: "Department of Public Works and Spatial Planning",
    address: "Jl. Pool Binamarga No. 2A Bogor",
    numberDate: "602/SPK/PRC- 015/PPK/PUPR/201 9 27/09/2019",
    value: "99.770.000",
    contract: "26/11/2019",
    handover: "26/11/2019",
  },
  {
    no: "56",
    field:
      "Inventory and Identification of B3 Waste Producing Businesses",
    subField: "Environment",
    location: "Bogor City",
    name: "Bogor City Environmental Service",
    address: "Jl. Paledang No. 43 Bogor",
    numberDate: "027/SPK/INVT.IDNT. LIMBAH B3/PPK/DLH/IX/201 9 30/09/2019",
    value: "80.795.000",
    contract: "29/11/2019",
    handover: "29/11/2019",
  },
  {
    no: "57",
    field:
      "Shop for RPBD Document Review Consultant Services",
    subField: "Study, Research and Technical Assistance Services",
    location: "Bogor City",
    name: "District Regional Disaster Management Agency. Bogor",
    address: "Jl. Raya Tegar Beriman Kab. Bogor",
    numberDate: "027/15.0002/79/SP K-BPBD/IX/2019 26/09/2019",
    value: "91.580.500",
    contract: "26/11/2019",
    handover: "26/11/2019",
  },
  {
    no: "58",
    field:
      "Technical Planning for Improvement of Roads, Bridges, Sidewalks and Site Drainage 3",
    subField: "Building and Landscape Environmental Design",
    location: "Bogor City",
    name: "Bogor City Public Works and Spatial Planning Department",
    address: "Jl. Pool Binamarga No. 2A Bogor",
    numberDate: "602/SPK/PRC- 011/PPK/PUPR/201 9 24/09/2019",
    value: "86.185.000",
    contract: "22/11/2019",
    handover: "22/11/2019",
  },
  {
    no: "59",
    field:
      "SID Water Resources Potential Development",
    subField: "Water Civil Engineering",
    location: "West Java",
    name: "Provincial Plantation Service. West Java",
    address: "Jl. Surapati No. 67 Bandung",
    numberDate: "027/1446/Banglin/2 019 24/10/2019",
    value: "36.019.500",
    contract: "18/11/2019",
    handover: "18/11/2019",
  },
  {
    no: "60",
    field:
      "Shop for Andalalin Manufacturing Consultancy Services",
    subField: "Transportation Civil Engineering",
    location: "Garut Regency",
    name: "Department of Industry, Trade, Energy and Mineral Resources",
    address: "Jl. Merdeka No. 219 Garut",
    numberDate: "027/60/SPK/PPK- Bidpas/2019 20/11/2019",
    value: "99.588.500",
    contract: "19/12/2019",
    handover: "19/12/2019",
  },
  {
    no: "61",
    field:
      "Update and Preparation of DPUPR Infrastructure Integration in South Denpasar District",
    subField: "Survey",
    location: "Denpasar City",
    name: "Denpasar City Public Works & Spatial Planning Department",
    address: "Jl. Gatot Subroto VI/J No. 24, Denpasar, Bali",
    numberDate: "620/6760/DPUPR 13/08/2019",
    value: "206.827.500",
    contract: "10/12/2019",
    handover: "03/12/2019",
  },
  {
    no: "62",
    field:
      "Preparation of Technical Instructions for Maintenance of Fishery Waste Water Treatment Installations (IPAL).",
    subField: "Study, Research and Technical / Environmental Assistance Services",
    location: "Jakarta",
    name: "Ministry of Environment & Forestry",
    address: "Jl. D.I. Panjaitan Kav. 24 Kebon Nanas, Jakarta",
    numberDate: "SPK.213/PPA.04/PP K/2019 11/10/2019",
    value: "74.525.000",
    contract: "09/12/2019",
    handover: "09/12/2019",
  },
  {
    no: "63",
    field:
      "Creation of a Cipta Karya Infrastructure Data Management System",
    subField: "Telematics",
    location: "Bintan Regency",
    name: "District Public Works and Spatial Planning Department. Bintan",
    address: "Jl. Raya Tanjungpinang- Tanjung Uban KM 42, Bandar Seri Bentan",
    numberDate: "05/SPK- PRCT/RDTR/APBDP/ 2019 22/10/2019",
    value: "98.899.000",
    contract: "20/12/2019",
    handover: "20/12/2019",
  },
  {
    no: "64",
    field:
      "Regional Planning Consultancy II",
    subField: "Regional Planning / Spatial Planning",
    location: "West Bandung Regency",
    name: "Department of Housing and Settlements",
    address: "Jl. Raya Padalarang- Cisarua Km 2 Desa Ngamprah- Kab.bandung",
    numberDate: "027/1003- SPK/PPK11/DISPERK IM/2019 19/06/2019",
    value: "44.880.000",
    contract: "19/06/2019",
    handover: "02/06/2019",
  },
  {
    no: "65",
    field:
      "Preparation of Disaster Risk Assessment (KRB)",
    subField: "Study, Research and Technical Assistance Services",
    location: "Sumedang Regency",
    name: "Regional Disaster Management Agency Service",
    address: "Jl. Empang no 1",
    numberDate: "010/SPK/PPK- KRB/BPBD/2019 13/11/2019",
    value: "97.240.000",
    contract: "13/11/2019",
    handover: "12/11/2019",
  },
  {
    no: "66",
    field:
      "Land Use Mapping of the Duchy – Cigasong Corridor",
    subField: "Survey / Mapping",
    location: "Majalengka Regency",
    name: "Department of Highways and Human Settlements for Spatial Planning",
    address: "Jl. KH. Abdul Halim No. 99-100 Majalengka",
    numberDate: "650/36/SPK/PPK.BID .TR/BMCK 18/10/2019",
    value: "99.660.000",
    contract: "16/12/2019",
    handover: "19/12/2019",
  },
  {
    no: "67",
    field:
      "UKL UPL Consultant Services",
    subField: "Environment",
    location: "Sukabumi",
    name: "Purabaya Community Health Center UPTD",
    address: "Jl. Raya Purabaya Km.39 Sukabumi",
    numberDate: "027/02/SPK- PPK/UKL- UPL/PUS.PURABAYA /2019 20/11/2019",
    value: "14.762.000",
    contract: "20/10/2019",
    handover: "20/10/2019",
  },
  {
    no: "68",
    field:
      "DPLH Preparation Consultancy Services",
    subField: "Environment",
    location: "Sukabumi",
    name: "Cijangkar Community Health Center UPTD",
    address: "Jl. Raya Sagaranten Km.12,5 Kec. Nyalindung Kab. Sukabumi",
    numberDate: "027/02/SPK- PPK/UKL- UPL/PUS.CIJKR/201 9 20/11/2019",
    value: "14.817.000",
    contract: "20/11/2019",
    handover: "20/11/2019",
  },
  {
    no: "69",
    field:
      "UKL UPL Preparation Consultancy Services",
    subField: "Environment",
    location: "Sukabumi",
    name: "Nyalindung Community Health Center UPTD",
    address: "Jl. Raya Nyalindung Km. 28 Kec. Nyalindung Kab. Sukabumi",
    numberDate: "027/02/SPK- PPK/UKL- UPL/PUS.NYAL/2019 20/11/2019",
    value: "14.817.000",
    contract: "20/11/2019",
    handover: "20/11/2019",
  },
];

export default project2019;
