const project2022 = [
    {
      no: "1",
      field:
        "Bank BJB Construction Planning Consultant Services",
      subField: "Civil Building/Architecture",
      location: "BJB Bank",
      name: "BJB Bank",
      address: "Jl. Naripan No. 12- 14 Bandung",
      numberDate: "0417/PLJ- PKS/2021 27/12/2021",
      value: "1.734.968.849",
      contract: "31/08/2022",
      handover: "31/08/2022",
    },
    {
      no: "2",
      field: "Construction Planning Consultant for the Advanced Development Technical Office of Class III Teminabuan Lapas T.A 2022",
      subField: "Civil Building/Architecture",
      location: "Teminabuan, South Sorong",
      name: "Class III Correctional Institution Teminabuan Kemenkumham RI West Papua Regional Office",
      address: "Jl. S. Konjol No. 33 Teminabuan Sorong Selatan",
      numberDate: "W31.PAS.PAS.07.P B.02.01-24 18/05/2022",
      value: "646.043.000",
      contract: "15/07/2022",
      handover: "15/07/2022",
    },
    {
      no: "3",
      field: "Promotion Building Development Planning Consultant and IKM Leading Product Development Center Kab. Sukabumi",
      subField: "Civil Building/Architecture",
      location: "Sukabumi",
      name: "Department of Trade and Industry of Sukabumi Regency",
      address: "Komplek Gelanggang Pemuda Cisaat- Sukabumi",
      numberDate: "027/03-KPA/SP- 20275609/DISDAG IN/2022 25/03/2022",
      value: "213.922.500",
      contract: "23/05/2022",
      handover: "23/05/2022",
    },
    {
      no: "4",
      field: "Making Situation Map of Forest Area Boundary in Pare-Besowo Forest Section",
      subField: "Survey/Map services",
      location: "Pare-Besowo forest",
      name: "Director General of Land and Space Surveys and Mapping of the Ministry of ATR/BPN",
      address: "Jl. Kuningan Barat I No. 1 Jakarta Selatan",
      numberDate: "123/KONTRAK/PP K-5543/VII/2022 12/07/2022",
      value: "1.590.019.500",
      contract: "19/09/2022",
      handover: "19/09/2022",
    },
    {
      no: "5",
      field: "Compilation of SPAM Strategic and Technical Plans, Policies - Compilation of Drinking Water Policy and Strategy Documents",
      subField: "Civil Water/Environmental",
      location: "Purwakarta",
      name: "Department of Housing and Residential Areas Kab. Purwakarta",
      address: "Jl. Kolonel Kornel Singawinata No. 116 Purwakarta",
      numberDate: "620/2.F.03/PPK/SP -PERKIM/VI/2022 22/06/2022",
      value: "295.470.900",
      contract: "21/10/2022",
      handover: "21/10/2022",
    },
    {
      no: "6",
      field: "RISPAL Document Compilation",
      subField: "Civil Water/Environmental",
      location: "Purwakarta",
      name: "Department of Housing and Residential Areas Kab. Purwakarta",
      address: "Jl. Kolonel Kornel Singawinata No. 116 Purwakarta",
      numberDate: "620/4.G.02/PPK/S PMK- PERKIM/III/2022 31/03/2022",
      value: "469.084.000",
      contract: "30/09/2022",
      handover: "30/09/2022",
    },
]

  export default project2022;
  