const project2018 = [
  {
    no: "1",
    field:
      "Monitoring Well Development Planning Consultancy",
    subField: "Water Civil Engineering Planning",
    location: "Bekasi City",
    name: "Bekasi City Environmental Service",
    address: "Jl. Jend. A. Yani No. 1",
    numberDate: "027/04-DED SUMUR/DinasLH.PPKL H 31-08-2018",
    value: "162.000.000",
    contract: "14/10/2018",
    handover: "14/10/2018",
  },
  {
    no: "2",
    field: "Data Center & Command Center Building Consultancy Services Kab. Tanah Laut Regency",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Tanah Laut Regency",
    name: "Diskominfo",
    address: "Jl. A. Syairani Komp. Perkantoran Pelaihari",
    numberDate: "027/10/SPK/PL/DISKO MINFO/2018 12/11/2018",
    value: "59.400.000",
    contract: "15/12/2018",
    handover: "15/12/2018",
  },
  {
    no: "3",
    field:
      "DED Drainage Channel Jl. Jakarta-Jl. Kiaracondong",
    subField: "Water Civil Engineering Planning",
    location: "Bandung City",
    name: "Bandung City Public Works Department",
    address: "Jl. Cianjur No. 34 Bandung",
    numberDate: "027/37.03/PL.03/SPK /PPKm/DPU/2018 9/10/2018",
    value: "48.785.000",
    contract: "7/11/2018",
    handover: "7/11/2018",
  },
  {
    no: "4",
    field:
      "Preparation of District Environmental Quality Index. East Belitung",
    subField: "Study Services. Research and Engineering/Environmental Assistance",
    location: "East Belitung Regency",
    name: "District Environmental Service. East Belitung",
    address: "Jl. Raya Manggar- Gantung Dusun Manggarawan Manggar",
    numberDate: "01/SPK/KONS- IKLH/DLH/2018 6/9/2018",
    value: "49.500.000",
    contract: "5/11/2018",
    handover: "31/10/2018",
  },
  {
    no: "5",
    field: "Study of the Potential of Construction Experts",
    subField: "Study Services. Research and Technical Assistance",
    location: "Banten Province",
    name: "Banten Province PUPR Service",
    address: "Jl. Syeh Nawawi Al Bantani Kota Serang Banten",
    numberDate: "900/187/SPK/BJK/DP UPR/X/2018 15/10/2018",
    value: "93.520.000",
    contract: "13/12/2018",
    handover: "13/12/2018",
  },
  {
    no: "6",
    field:
      "Preparation of Reservoir Management and Conservation Profiles. Embung. Sites and other water storage buildings",
    subField: "Water Civil Engineering Planning",
    location: "Banten Province",
    name: "Banten Province PUPR Service",
    address: "Jl. Syeh Nawawi Al Bantani Kota Serang Banten",
    numberDate: "900/SP.46.4.9/PJSA- DPUPR/2018 15/11/2018",
    value: "36.490.000",
    contract: "14/12/2018",
    handover: "7/11/2018",
  },
  {
    no: "7",
    field:
      "Shopping Print Activities for Preparing Guidebooks for Giving Awards for West Java Youth",
    subField: "Other Services",
    location: "West Java Province",
    name: "Provincial Youth and Sports Department. West Java",
    address: "Jl. Pacuan Kuda No. 140 Arcamanik. Bandung",
    numberDate: "27/SP/Sarpras Kesejahteraan/2018 28/11/2018",
    value: "18.100.000",
    contract: "12/12/2018",
    handover: "12/12/2018",
  },
  {
    no: "8",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Sukamaju District. Ds Warga Jaya and Ds Rengasjajar District. Cigudeg",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0028/SPK/AM- PL/PUPR/2018 2/11/2018",
    value: "28.935.000",
    contract: "26/11/2018",
    handover: "26/11/2018",
  },
  {
    no: "9",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Rabak (Kp. Rabak) Kec. Rumpin",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0027/SPK/AM- PL/PUPR/2018 31/10/2018",
    value: "9.355.000",
    contract: "24/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "10",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Jasinga District. Jasinga",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0030/SPK/AM- PL/PUPR/2018 1/11/2018",
    value: "9.355.000",
    contract: "25/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "11",
    field:
      "Planning for Procurement & Installation of Drinking Water/Clean Water Suggestion Pipes in Ds Malasari & Ds Curug Bitung District. Bear it",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.01- 30.0008/SPK/AM- PL/PUPR/2018 31/10/2018",
    value: "25.594.000",
    contract: "24/11/2018",
    handover: "23/11/2018",
  },
  {
    no: "12",
    field:
      "SPAM Development Planning in Ds. Kiarasari. Etc. Sukamulih. & Etc. Sukajaya District. Sukajaya",
    subField: "Water Civil Engineering Planning",
    location: "Bogor Regency",
    name: "District Public Works & Spatial Planning Department. Bogor",
    address: "Jl. Tegar Beriman Kel. Tengah Kec. Cibonong Kab. Bogor",
    numberDate: "690/A.03- 30.0005/SPK/AM- PL/PUPR/2018 2/11/2018",
    value: "42.645.000",
    contract: "26/11/2018",
    handover: "26/11/2018",
  },
  {
    no: "13",
    field:
      "Preparation of FS and DED for Small Scale Business Activities in the Kapuas Watershed",
    subField: "Study Services. Research and Technical Assistance",
    location: "Ministry of Environment & Forestry",
    name: "DIRECTOR GENERAL of Environmental Damage and Control",
    address: "Jl. D.I. Panjaitan Kav. 24. Kebon Nanas. Jakarta",
    numberDate: "SPK-1056/PPA/PPK- LU/2018 12/10/2018",
    value: "99.770.000",
    contract: "10/12/2018",
    handover: "10/12/2018",
  },
  {
    no: "14",
    field:
      "Data collection and preparation of a normative list of residents for land control within ROW boundaries for the construction of a double track railway between Bogor - Batutulis",
    subField: "Survey",
    location: "Ministry of Transportation",
    name: "DIRECTOR GENERAL of Railways",
    address: "Jl. Raya Gedebage No. 68 Bandung",
    numberDate: "PL.202/04/02/PPK- PP/BTKA- JABAR/PNTN/X-18 1/10/2018",
    value: "195.210.000",
    contract: "29/11/2018",
    handover: "1/12/2018",
  },
  {
    no: "15",
    field:
      "Preliminary Survey and Technical Coordination for the Implementation of the Kulon Progo Airport Public Train using the PPP Scheme",
    subField: "Survey",
    location: "Ministry of Transportation",
    name: "DIRECTOR GENERAL of Railways",
    address: "Graha Jatibaru Blok C-7 Jl. Jatibaru Timur No. 56A Cideng- Jakarta",
    numberDate: "03/JL- PDK/LLA.KA/XI/2018 30/11/2018",
    value: "176.209.000",
    contract: "31/12/2018",
    handover: "31/12/2018",
  },
  {
    no: "16",
    field:
      "Cijerah Community Health Center Planning Consultant - Cijerah Community Health Center Development Planning Consultant",
    subField: "Architectural Planning / Building Civil Engineering",
    location: "Bandung City",
    name: "Bandung City Health Department",
    address: "Jl. Citarum No. 34 Bandung",
    numberDate: "027/090.09/PPK.B- Dinkes/2018 17/09/2018",
    value: "98.560.000",
    contract: "15/11/2018",
    handover: "15/11/2018",
  },
];

export default project2018;
